"""
app/db/models/question.py

Question Bank models for Mindexa.

Tables defined here:
    question                     — A reusable question owned by a lecturer
    question_option              — Answer options for closed question types
    question_blank               — Blank definitions for fill-in-the-blank questions
    assessment_question           — Junction: question ↔ assessment (with per-assessment overrides)
    ai_generation_batch          — A single AI generation request session
    ai_generated_question        — A question candidate generated by AI
    ai_question_review           — Lecturer decision on each AI-generated candidate
    question_bank_entry           — The lecturer's question bank view
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import Column, ForeignKey, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlmodel import Field, Relationship

from app.core.constants import GradingMode
from app.db.base import BaseModel
from app.db.enums import (
    AIBatchStatus,
    AIQuestionDecision,
    DifficultyLevel,
    QuestionAddedVia,
    QuestionSourceType,
    QuestionType,
)
from app.db.mixins import composite_index

if TYPE_CHECKING:
    from app.db.models.assessment import Assessment, AssessmentSection, Rubric
    from app.db.models.attempt import StudentResponse


# ─────────────────────────────────────────────────────────────────────────────
# QUESTION
# ─────────────────────────────────────────────────────────────────────────────

class Question(BaseModel, table=True):
    """
    A reusable question owned by a lecturer.
    """

    __tablename__ = "question"

    __table_args__ = (
        # Fast subject-filtered bank queries
        composite_index("question", "subject_id", "question_type", "is_deleted"),
        composite_index("question", "subject_id", "difficulty", "is_deleted"),
        composite_index("question", "source_type", "is_approved", "is_deleted"),
        # Lecturer's own questions view
        composite_index("question", "created_by_id", "is_in_question_bank"),
        # Source traceability
        composite_index("question", "source_assessment_id", "source_type"),
        composite_index("question", "source_ai_batch_id"),
        # Parent-child lineage
        composite_index("question", "parent_question_id"),
    )

    created_by_id: uuid.UUID = Field(nullable=False, index=True)

    subject_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("subject.id", ondelete="SET NULL"), nullable=True, index=True)
    )

    question_type: QuestionType = Field(nullable=False, index=True)
    content: str = Field(nullable=False)
    explanation: str | None = Field(default=None, nullable=True)

    marks: int = Field(default=1, nullable=False)
    difficulty: DifficultyLevel = Field(default=DifficultyLevel.MEDIUM, nullable=False, index=True)
    grading_mode: str = Field(default=GradingMode.AUTO.value, nullable=False, index=True)
    topic_tag: str | None = Field(default=None, nullable=True, max_length=100, index=True)

    rubric_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("rubric.id", ondelete="SET NULL"), nullable=True, index=True)
    )

    source_type: QuestionSourceType = Field(default=QuestionSourceType.MANUAL, nullable=False, index=True)
    source_assessment_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("assessment.id", ondelete="SET NULL"), nullable=True, index=True)
    )
    source_ai_batch_id: uuid.UUID | None = Field(default=None, nullable=True, index=True)
    ai_action_log_id: uuid.UUID | None = Field(default=None, nullable=True, index=True)

    is_approved: bool = Field(default=False, nullable=False, index=True)
    approved_by_id: uuid.UUID | None = Field(default=None, nullable=True)
    approved_at: datetime | None = Field(default=None, nullable=True)
    is_shared: bool = Field(default=False, nullable=False, index=True)
    is_active: bool = Field(default=True, nullable=False, index=True)

    is_in_question_bank: bool = Field(default=False, nullable=False, index=True)
    bank_added_at: datetime | None = Field(default=None, nullable=True)
    bank_added_by_id: uuid.UUID | None = Field(default=None, nullable=True)

    version: int = Field(default=1, nullable=False)
    parent_question_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("question.id", ondelete="SET NULL"), nullable=True, index=True)
    )

    # ── Relationships ─────────────────────────────────────────────────────────

    rubric: Optional["Rubric"] = Relationship()

    options: List["QuestionOption"] = Relationship(
        back_populates="question",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "order_by": "QuestionOption.order_index"},
    )
    blanks: List["QuestionBlank"] = Relationship(
        back_populates="question",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "order_by": "QuestionBlank.blank_index"},
    )
    assessment_questions: List["AssessmentQuestion"] = Relationship(back_populates="question")
    bank_entry: Optional["QuestionBankEntry"] = Relationship(
        back_populates="question",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )
    responses: List["StudentResponse"] = Relationship(back_populates="question")


# ─────────────────────────────────────────────────────────────────────────────
# QUESTION OPTION
# ─────────────────────────────────────────────────────────────────────────────

class QuestionOption(BaseModel, table=True):
    __tablename__ = "question_option"

    __table_args__ = (
        composite_index("question_option", "question_id", "order_index"),
        composite_index("question_option", "question_id", "is_correct"),
    )

    question_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("question.id", ondelete="CASCADE"), nullable=False, index=True)
    )
    content: str = Field(nullable=False)
    is_correct: bool | None = Field(default=None, nullable=True)
    match_key: str | None = Field(default=None, nullable=True, max_length=500)
    match_value: str | None = Field(default=None, nullable=True, max_length=500)
    order_index: int = Field(nullable=False)

    question: Optional["Question"] = Relationship(back_populates="options")


# ─────────────────────────────────────────────────────────────────────────────
# QUESTION BLANK
# ─────────────────────────────────────────────────────────────────────────────

class QuestionBlank(BaseModel, table=True):
    __tablename__ = "question_blank"

    __table_args__ = (
        UniqueConstraint("question_id", "blank_index", name="uq_question_blank_question_blank_index"),
        composite_index("question_blank", "question_id"),
    )

    question_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("question.id", ondelete="CASCADE"), nullable=False, index=True)
    )
    blank_index: int = Field(nullable=False)
    accepted_answers: list[str] = Field(
        default_factory=list,
        sa_column=Column(JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    )
    case_sensitive: bool = Field(default=False, nullable=False)

    question: Optional["Question"] = Relationship(back_populates="blanks")


# ─────────────────────────────────────────────────────────────────────────────
# ASSESSMENT QUESTION (junction)
# ─────────────────────────────────────────────────────────────────────────────

class AssessmentQuestion(BaseModel, table=True):
    __tablename__ = "assessment_question"

    __table_args__ = (
        UniqueConstraint("assessment_id", "question_id", name="uq_assessment_question_assessment_question"),
        UniqueConstraint("assessment_id", "assessment_section_id", "order_index", name="uq_assessment_question_assessment_section_order"),
        composite_index("assessment_question", "assessment_id", "order_index"),
        composite_index("assessment_question", "assessment_id", "added_via"),
        composite_index("assessment_question", "question_id"),
    )

    assessment_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("assessment.id", ondelete="CASCADE"), nullable=False, index=True)
    )
    question_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("question.id", ondelete="RESTRICT"), nullable=False, index=True)
    )
    assessment_section_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("assessment_section.id", ondelete="SET NULL"), nullable=True, index=True)
    )
    order_index: int = Field(nullable=False)
    marks_override: int | None = Field(default=None, nullable=True)
    is_required: bool = Field(default=True, nullable=False)

    added_via: QuestionAddedVia = Field(default=QuestionAddedVia.MANUAL_WRITE, nullable=False, index=True)
    ai_review_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("ai_question_review.id", ondelete="SET NULL"), nullable=True, index=True)
    )
    bank_entry_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("question_bank_entry.id", ondelete="SET NULL"), nullable=True, index=True)
    )

    question: Optional["Question"] = Relationship(back_populates="assessment_questions")
    assessment: Optional["Assessment"] = Relationship(back_populates="assessment_questions")
    assessment_section: Optional["AssessmentSection"] = Relationship(back_populates="assessment_questions")
    ai_review: Optional["AIQuestionReview"] = Relationship(back_populates="assessment_question")
    bank_entry: Optional["QuestionBankEntry"] = Relationship(back_populates="assessment_questions")


# ─────────────────────────────────────────────────────────────────────────────
# AI GENERATION BATCH
# ─────────────────────────────────────────────────────────────────────────────

class AIGenerationBatch(BaseModel, table=True):
    __tablename__ = "ai_generation_batch"

    created_by_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("user.id", ondelete="RESTRICT"), nullable=False, index=True)
    )
    assessment_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("assessment.id", ondelete="CASCADE"), nullable=True, index=True)
    )
    question_type: str = Field(nullable=False)
    difficulty: str = Field(nullable=False)
    total_requested: int = Field(nullable=False)
    subject: str | None = Field(default=None, nullable=True)
    topic: str | None = Field(default=None, nullable=True)
    bloom_level: str | None = Field(default=None, nullable=True)
    full_prompt: str | None = Field(default=None, nullable=True)
    additional_context: str | None = Field(default=None, nullable=True)

    status: AIBatchStatus = Field(default=AIBatchStatus.PENDING, nullable=False, index=True)
    total_generated: int = Field(default=0, nullable=False)
    total_failed: int = Field(default=0, nullable=False)
    started_at: datetime | None = Field(default=None, nullable=True)
    completed_at: datetime | None = Field(default=None, nullable=True)
    error_message: str | None = Field(default=None, nullable=True)
    ai_model_used: str | None = Field(default=None, nullable=True)
    ai_provider: str | None = Field(default=None, nullable=True)
    total_tokens_used: int | None = Field(default=None, nullable=True)

    assessment: Optional["Assessment"] = Relationship(back_populates="ai_generation_batches")
    generated_questions: List["AIGeneratedQuestion"] = Relationship(
        back_populates="batch",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )


# ─────────────────────────────────────────────────────────────────────────────
# AI GENERATED QUESTION
# ─────────────────────────────────────────────────────────────────────────────

class AIGeneratedQuestion(BaseModel, table=True):
    __tablename__ = "ai_generated_question"

    batch_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("ai_generation_batch.id", ondelete="CASCADE"), nullable=False, index=True)
    )
    generated_content: str = Field(nullable=False)
    question_type: str = Field(nullable=False)
    difficulty: str = Field(nullable=False)
    raw_prompt: str | None = Field(default=None, nullable=True)
    parsed_successfully: bool = Field(default=False, nullable=False)
    parsed_question_text: str | None = Field(default=None, nullable=True)
    parsed_options_json: str | None = Field(default=None, nullable=True)
    parsed_explanation: str | None = Field(default=None, nullable=True)
    parse_error: str | None = Field(default=None, nullable=True)
    review_status: AIQuestionDecision = Field(default=AIQuestionDecision.PENDING, nullable=False, index=True)

    batch: Optional["AIGenerationBatch"] = Relationship(back_populates="generated_questions")
    review: Optional["AIQuestionReview"] = Relationship(
        back_populates="generated_question",
        sa_relationship_kwargs={"uselist": False},
    )


# ─────────────────────────────────────────────────────────────────────────────
# AI QUESTION REVIEW
# ─────────────────────────────────────────────────────────────────────────────

class AIQuestionReview(BaseModel, table=True):
    __tablename__ = "ai_question_review"

    ai_question_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("ai_generated_question.id", ondelete="CASCADE"), nullable=False, index=True)
    )
    reviewer_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("user.id", ondelete="RESTRICT"), nullable=False, index=True)
    )
    decision: str = Field(nullable=False, index=True)
    modified_question_text: str | None = Field(default=None, nullable=True)
    modified_options_json: str | None = Field(default=None, nullable=True)
    modified_explanation: str | None = Field(default=None, nullable=True)
    reviewer_notes: str | None = Field(default=None, nullable=True)
    reviewed_at: datetime = Field(nullable=False)

    generated_question: Optional["AIGeneratedQuestion"] = Relationship(back_populates="review")
    assessment_question: Optional["AssessmentQuestion"] = Relationship(back_populates="ai_review")


# ─────────────────────────────────────────────────────────────────────────────
# QUESTION BANK ENTRY
# ─────────────────────────────────────────────────────────────────────────────

class QuestionBankEntry(BaseModel, table=True):
    __tablename__ = "question_bank_entry"

    __table_args__ = (
        UniqueConstraint("question_id", "added_by_id", name="uq_question_bank_entry_question_lecturer"),
        composite_index("question_bank_entry", "added_by_id", "subject_id", "is_active"),
        composite_index("question_bank_entry", "added_by_id", "source_type", "is_active"),
        composite_index("question_bank_entry", "added_by_id", "difficulty", "is_active"),
        composite_index("question_bank_entry", "added_by_id", "times_used"),
    )

    question_id: uuid.UUID = Field(
        sa_column=Column(UUID(as_uuid=True), ForeignKey("question.id", ondelete="RESTRICT"), nullable=False, index=True)
    )
    added_by_id: uuid.UUID = Field(nullable=False, index=True)

    subject_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("subject.id", ondelete="SET NULL"), nullable=True, index=True)
    )
    difficulty: DifficultyLevel | None = Field(default=None, nullable=True, index=True)
    source_type: QuestionSourceType = Field(default=QuestionSourceType.MANUAL, nullable=False, index=True)
    source_assessment_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(UUID(as_uuid=True), ForeignKey("assessment.id", ondelete="SET NULL"), nullable=True, index=True)
    )

    times_used: int = Field(default=0, nullable=False)
    last_used_at: datetime | None = Field(default=None, nullable=True)
    is_active: bool = Field(default=True, nullable=False, index=True)

    question: Optional["Question"] = Relationship(back_populates="bank_entry")
    assessment_questions: List["AssessmentQuestion"] = Relationship(back_populates="bank_entry")


# Backward-compatible alias used by the model registry and older repositories.
AIQuestionGenerationBatch = AIGenerationBatch
