"""
app/db/enums.py

Every platform-wide enumeration for Mindexa.

Rules:
  - All enums use str as the base type so they are JSON-serialisable
    and PostgreSQL-compatible without extra converters.
  - Integer enums (WarningLevel) use int base type only where ordering
    by value is semantically meaningful.
  - Never define enums inline on models — always import from here.
  - PostgreSQL native ENUM types are NOT used; instead, VARCHAR columns
    with CHECK constraints are generated by SQLAlchemy. This avoids the
    painful ALTER TYPE migrations required when adding enum values in
    PostgreSQL native enums.
"""

from enum import Enum

# ─────────────────────────────────────────────────────────────────────────────
# AUTH & IDENTITY
# ─────────────────────────────────────────────────────────────────────────────

class UserRole(str, Enum):
    STUDENT = "student"
    LECTURER = "lecturer"
    ADMIN = "admin"


class UserStatus(str, Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    SUSPENDED = "suspended"
    PENDING_VERIFICATION = "pending_verification"


class TokenType(str, Enum):
    ACCESS = "access"
    REFRESH = "refresh"
    PASSWORD_RESET = "password_reset"
    EMAIL_VERIFICATION = "email_verification"


# ─────────────────────────────────────────────────────────────────────────────
# ACADEMIC STRUCTURE
# ─────────────────────────────────────────────────────────────────────────────

class AcademicPeriodType(str, Enum):
    SEMESTER = "semester"
    TRIMESTER = "trimester"
    QUARTER = "quarter"
    YEAR = "year"


class EnrollmentStatus(str, Enum):
    ACTIVE = "active"
    WITHDRAWN = "withdrawn"
    COMPLETED = "completed"
    DEFERRED = "deferred"


class LecturerAssignmentRole(str, Enum):
    PRIMARY = "primary"
    ASSISTANT = "assistant"
    SUPERVISOR = "supervisor"


# ─────────────────────────────────────────────────────────────────────────────
# ASSESSMENT MANAGEMENT
# ─────────────────────────────────────────────────────────────────────────────

class AssessmentType(str, Enum):
    FORMATIVE = "formative"
    CAT = "cat"
    SUMMATIVE = "summative"
    HOMEWORK = "homework"
    GROUP_WORK = "group_work"
    REASSESSMENT = "reassessment"


class AssessmentStatus(str, Enum):
    DRAFT = "draft"
    PUBLISHED = "published"
    ACTIVE = "active"
    CLOSED = "closed"
    ARCHIVED = "archived"


class GradingMode(str, Enum):
    AUTO = "auto"
    SEMI = "semi"
    MANUAL = "manual"
    RUBRIC = "rubric"


class ResultReleaseMode(str, Enum):
    IMMEDIATE = "immediate"
    DELAYED = "delayed"
    SCHEDULED = "scheduled"


class SupervisorRole(str, Enum):
    PRIMARY = "primary"
    ASSISTANT = "assistant"


class BlueprintRuleType(str, Enum):
    MIN_QUESTIONS = "min_questions"
    MAX_QUESTIONS = "max_questions"
    EXACT_QUESTIONS = "exact_questions"
    MARKS_TOTAL = "marks_total"
    DIFFICULTY_RATIO = "difficulty_ratio"
    QUESTION_TYPE_REQUIRED = "question_type_required"
    QUESTION_TYPE_EXCLUDED = "question_type_excluded"


# ─────────────────────────────────────────────────────────────────────────────
# QUESTION BANK
# ─────────────────────────────────────────────────────────────────────────────

class QuestionType(str, Enum):
    MCQ = "mcq"
    TRUE_FALSE = "true_false"
    SHORT_ANSWER = "short_answer"
    ESSAY = "essay"
    MATCHING = "matching"
    FILL_BLANK = "fill_blank"
    COMPUTATIONAL = "computational"
    CASE_STUDY = "case_study"
    ORDERING = "ordering"


class DifficultyLevel(str, Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"


class QuestionSourceType(str, Enum):
    """
    Tracks how a question entered the system.

    manual               — Lecturer typed it directly in the assessment builder or bank.
    ai_generated         — Created by an AI agent; may have been modified by lecturer.
    assessment_auto_saved — Automatically added to the bank when the containing
                           assessment was published.
    imported             — Future: batch-imported from an external file or system.
    """
    MANUAL = "manual"
    AI_GENERATED = "ai_generated"
    ASSESSMENT_AUTO_SAVED = "assessment_auto_saved"
    IMPORTED = "imported"


class QuestionAddedVia(str, Enum):
    """
    Tracks how a question entered a specific assessment.
    Stored on assessment_question.added_via.
    """
    MANUAL_WRITE = "manual_write"
    BANK_INSERT = "bank_insert"
    AI_GENERATED_ACCEPTED = "ai_generated_accepted"
    AI_GENERATED_MODIFIED = "ai_generated_modified"


class AIBatchStatus(str, Enum):
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"
    PARTIALLY_COMPLETED = "partially_completed"


class AIQuestionDecision(str, Enum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    MODIFIED = "modified"
    REJECTED = "rejected"


# ─────────────────────────────────────────────────────────────────────────────
# ATTEMPT & SUBMISSION
# ─────────────────────────────────────────────────────────────────────────────

class AttemptStatus(str, Enum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    SUBMITTED = "submitted"
    AUTO_SUBMITTED = "auto_submitted"
    ABANDONED = "abandoned"
    PENDING ="pending"


class SubmissionGradingMode(str, Enum):
    """
    The grading mode that was actually applied to this submission.
    Distinct from assessment-level GradingMode — a single assessment may
    use different modes per question type.
    """
    AUTO = "auto"
    AI_SUGGESTED = "ai_suggested"
    LECTURER_MANUAL = "lecturer_manual"
    RUBRIC = "rubric"


class SubmissionStatus(str, Enum):
    SUBMITTED = "submitted"
    GRADING_QUEUED = "grading_queued"
    AUTO_GRADED = "auto_graded"
    AI_SUGGESTED = "ai_suggested"
    AWAITING_REVIEW = "awaiting_review"
    REVIEWER_APPROVED = "reviewer_approved"
    FINAL_RELEASED = "final_released"
    UNDER_APPEAL = "under_appeal"
    PENDING_GRADING = "pending_grading"
    GRADING_FAILED = "grading_failed"


class AppealStatus(str, Enum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    REVISED = "revised"
    SUBMITTED = "submitted"




# ─────────────────────────────────────────────────────────────────────────────
# INTEGRITY MONITORING
# ─────────────────────────────────────────────────────────────────────────────

class IntegrityEventType(str, Enum):
    FULLSCREEN_EXIT = "fullscreen_exit"
    FULLSCREEN_ENTER = "fullscreen_enter"
    TAB_SWITCH = "tab_switch"
    WINDOW_BLUR = "window_blur"
    WINDOW_FOCUS = "window_focus"
    VISIBILITY_HIDDEN = "visibility_hidden"
    COPY_ATTEMPT = "copy_attempt"
    PASTE_ATTEMPT = "paste_attempt"
    RIGHT_CLICK = "right_click"
    EXTENDED_INACTIVITY = "extended_inactivity"
    RECONNECT = "reconnect"
    UNUSUAL_KEYPRESS = "unusual_keypress"


class IntegrityRiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class IntegrityFlagRaisedBy(str, Enum):
    SYSTEM = "system"
    SUPERVISOR = "supervisor"
    AI_AGENT = "ai_agent"


class IntegrityFlagStatus(str, Enum):
    OPEN = "open"
    REVIEWED = "reviewed"
    DISMISSED = "dismissed"
    ESCALATED = "escalated"


class WarningLevel(int, Enum):
    """
    Integer enum — ordering by value is semantically meaningful.
    Level 3 automatically triggers an integrity_flag.
    """
    NONE = 0
    WARNING_1 = 1
    WARNING_2 = 2
    WARNING_3 = 3


# ─────────────────────────────────────────────────────────────────────────────
# NOTIFICATIONS & SCHEDULING
# ─────────────────────────────────────────────────────────────────────────────

class NotificationType(str, Enum):
    ASSESSMENT_PUBLISHED = "assessment_published"
    ASSESSMENT_REMINDER = "assessment_reminder"
    RESULT_RELEASED = "result_released"
    FEEDBACK_RELEASED = "feedback_released"
    SUBMISSION_RECEIVED = "submission_received"
    GRADING_REQUIRED = "grading_required"
    INTEGRITY_ALERT = "integrity_alert"
    APPEAL_SUBMITTED = "appeal_submitted"
    APPEAL_RESOLVED = "appeal_resolved"
    DEADLINE_EXTENDED = "deadline_extended"
    REASSESSMENT_SCHEDULED = "reassessment_scheduled"


class NotificationChannel(str, Enum):
    IN_APP = "in_app"
    EMAIL = "email"
    BOTH = "both"


class ScheduledEventType(str, Enum):
    ASSESSMENT_WINDOW_OPEN = "assessment_window_open"
    ASSESSMENT_DEADLINE = "assessment_deadline"
    RESULT_RELEASE = "result_release"
    REASSESSMENT_WINDOW = "reassessment_window"
    REVIEW_DEADLINE = "review_deadline"


# ─────────────────────────────────────────────────────────────────────────────
# STUDENT RESOURCES
# ─────────────────────────────────────────────────────────────────────────────

class ResourceCategory(str, Enum):
    LECTURE_NOTES = "lecture_notes"
    PAST_PAPER = "past_paper"
    PERSONAL_NOTES = "personal_notes"
    OTHER = "other"
    GENERAL = "general"


class ResourceProcessingStatus(str, Enum):
    PENDING = "pending"
    PROCESSED = "processed"
    FAILED = "failed"


# ─────────────────────────────────────────────────────────────────────────────
# AI TRACEABILITY
# ─────────────────────────────────────────────────────────────────────────────

class AIActionType(str, Enum):
    GENERATE_QUESTIONS = "generate_questions"
    GENERATE_RUBRIC = "generate_rubric"
    GENERATE_ASSESSMENT_DRAFT = "generate_assessment_draft"
    GRADE_RESPONSE = "grade_response"
    SUGGEST_FEEDBACK = "suggest_feedback"
    ANALYZE_INTEGRITY = "analyze_integrity"
    STUDY_SUPPORT = "study_support"
    DOCUMENT_SUMMARY = "document_summary"
    ANSWER_KEY_GENERATION = "answer_key_generation"


class AIActionStatus(str, Enum):
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"
    INITIATED = "initiated"


class AIGradeDecision(str, Enum):
    NOT_APPLICABLE = "not_applicable"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    MODIFIED = "modified"
    PENDING = "pending"




# ─────────────────────────────────────────────────────────────────────────────
# AUDIT & SECURITY
# ─────────────────────────────────────────────────────────────────────────────

class SecurityEventType(str, Enum):
    FAILED_LOGIN = "failed_login"
    ACCOUNT_LOCKED = "account_locked"
    TOKEN_REVOKED = "token_revoked"
    SUSPICIOUS_IP = "suspicious_ip"
    PASSWORD_RESET_REQUESTED = "password_reset_requested"
    ROLE_CHANGED = "role_changed"
    ACCOUNT_SUSPENDED = "account_suspended"


class SecurityEventSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


# ─────────────────────────────────────────────────────────────────────────────
# PAGINATION (not an enum — but lives here as a shared constant)
# ─────────────────────────────────────────────────────────────────────────────

DEFAULT_PAGE_SIZE: int = 20
MAX_PAGE_SIZE: int = 100
MIN_PAGE_SIZE: int = 1
