"""
app/db/enums.py

All SQLModel/SQLAlchemy-compatible enum definitions for Mindexa Platform.
Aligned with database ENUM values (UPPERCASE).
"""

from enum import Enum


class UserRole(str, Enum):
    STUDENT = "STUDENT"
    LECTURER = "LECTURER"
    ADMIN = "ADMIN"


class UserStatus(str, Enum):
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"
    GRADUATED = "GRADUATED"


class TokenType(str, Enum):
    ACCESS = "ACCESS"
    REFRESH = "REFRESH"
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
    PASSWORD_RESET = "PASSWORD_RESET"


class AcademicPeriodType(str, Enum):
    SEMESTER = "SEMESTER"
    TRIMESTER = "TRIMESTER"
    QUARTER = "QUARTER"
    YEAR = "YEAR"


class LecturerAssignmentRole(str, Enum):
    PRIMARY = "PRIMARY"
    ASSISTANT = "ASSISTANT"
    SUPERVISOR = "SUPERVISOR"


class EnrollmentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    WITHDRAWN = "WITHDRAWN"
    COMPLETED = "COMPLETED"
    DEFERRED = "DEFERRED"


class AssessmentType(str, Enum):
    FORMATIVE = "FORMATIVE"
    CAT = "CAT"
    SUMMATIVE = "SUMMATIVE"
    HOMEWORK = "HOMEWORK"
    GROUP_WORK = "GROUP_WORK"
    REASSESSMENT = "REASSESSMENT"


class AssessmentStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class GradingMode(str, Enum):
    AUTO = "AUTO"
    MANUAL = "MANUAL"
    RUBRIC = "RUBRIC"
    SEMI = "SEMI"


class ResultReleaseMode(str, Enum):
    IMMEDIATE = "IMMEDIATE"
    DELAYED = "DELAYED"
    SCHEDULED = "SCHEDULED"


class SupervisorRole(str, Enum):
    PRIMARY = "PRIMARY"
    ASSISTANT = "ASSISTANT"


class BlueprintRuleType(str, Enum):
    TOTAL_QUESTIONS = "TOTAL_QUESTIONS"
    MIN_QUESTIONS = "MIN_QUESTIONS"
    MAX_QUESTIONS = "MAX_QUESTIONS"
    EXACT_QUESTIONS = "EXACT_QUESTIONS"
    MARKS_TOTAL = "MARKS_TOTAL"
    DIFFICULTY_RATIO = "DIFFICULTY_RATIO"
    DIFFICULTY_DISTRIBUTION = "DIFFICULTY_DISTRIBUTION"
    QUESTION_TYPE_REQUIRED = "QUESTION_TYPE_REQUIRED"
    QUESTION_TYPE_EXCLUDED = "QUESTION_TYPE_EXCLUDED"
    QUESTION_TYPE_DISTRIBUTION = "QUESTION_TYPE_DISTRIBUTION"
    BLOOM_LEVEL_REQUIRED = "BLOOM_LEVEL_REQUIRED"
    BLOOM_DISTRIBUTION = "BLOOM_DISTRIBUTION"
    TIME_ESTIMATE = "TIME_ESTIMATE"
    MARKS_DISTRIBUTION = "MARKS_DISTRIBUTION"
    SECTION_MARKS = "SECTION_MARKS"
    TOPIC_COVERAGE = "TOPIC_COVERAGE"

    @classmethod
    def all_types(cls) -> set[str]:
        return {member.value for member in cls}


class QuestionType(str, Enum):
    MCQ = "MCQ"
    TRUE_FALSE = "TRUE_FALSE"
    SHORT_ANSWER = "SHORT_ANSWER"
    ESSAY = "ESSAY"
    MATCHING = "MATCHING"
    FILL_BLANK = "FILL_BLANK"
    COMPUTATIONAL = "COMPUTATIONAL"
    CASE_STUDY = "CASE_STUDY"
    ORDERING = "ORDERING"


class DifficultyLevel(str, Enum):
    EASY = "EASY"
    MEDIUM = "MEDIUM"
    HARD = "HARD"


class QuestionSourceType(str, Enum):
    MANUAL = "MANUAL"
    AI_GENERATED = "AI_GENERATED"
    ASSESSMENT_AUTO_SAVED = "ASSESSMENT_AUTO_SAVED"
    IMPORTED = "IMPORTED"


class QuestionAddedVia(str, Enum):
    MANUAL_WRITE = "MANUAL_WRITE"
    BANK_INSERT = "BANK_INSERT"
    AI_GENERATED_ACCEPTED = "AI_GENERATED_ACCEPTED"
    AI_GENERATED_MODIFIED = "AI_GENERATED_MODIFIED"


class AIActionType(str, Enum):
    GENERATE_QUESTIONS = "GENERATE_QUESTIONS"
    GENERATE_RUBRIC = "GENERATE_RUBRIC"
    GENERATE_ASSESSMENT_DRAFT = "GENERATE_ASSESSMENT_DRAFT"
    GRADE_RESPONSE = "GRADE_RESPONSE"
    SUGGEST_FEEDBACK = "SUGGEST_FEEDBACK"
    ANALYZE_INTEGRITY = "ANALYZE_INTEGRITY"
    STUDY_SUPPORT = "STUDY_SUPPORT"
    DOCUMENT_SUMMARY = "DOCUMENT_SUMMARY"
    ANSWER_KEY_GENERATION = "ANSWER_KEY_GENERATION"
    # Old names for compatibility if needed
    QUESTION_GENERATION = "QUESTION_GENERATION"
    GRADING_SUGGESTION = "GRADING_SUGGESTION"
    RUBRIC_SUGGESTION = "RUBRIC_SUGGESTION"
    INTEGRITY_ANALYSIS = "INTEGRITY_ANALYSIS"
    ASSESSMENT_DRAFT = "ASSESSMENT_DRAFT"
    FEEDBACK_DRAFT = "FEEDBACK_DRAFT"
    EMBEDDING = "EMBEDDING"


class AIActionStatus(str, Enum):
    PENDING = "PENDING"
    INITIATED = "INITIATED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RATE_LIMITED = "RATE_LIMITED"


class AIBatchStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    PARTIAL_FAILURE = "PARTIAL_FAILURE"
    FAILED = "FAILED"


class AIQuestionDecision(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    APPROVED = "ACCEPTED"
    EDITED = "MODIFIED"
    NEEDS_REVISION = "NEEDS_REVISION"


class AIGradeDecision(str, Enum):
    PENDING = "PENDING"
    SUGGESTED = "SUGGESTED"
    ACCEPTED = "ACCEPTED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class SubmissionStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    AUTO_SUBMITTED = "AUTO_SUBMITTED"
    PENDING_GRADING = "PENDING_GRADING"
    AUTO_GRADED = "AUTO_GRADED"
    AI_SUGGESTED = "AI_SUGGESTED"
    LECTURER_REVIEWED = "LECTURER_REVIEWED"
    FINAL = "FINAL"
    GRADED = "GRADED"
    UNDER_REVIEW = "UNDER_REVIEW"
    RELEASED = "RELEASED"
    REVIEWER_APPROVED = "REVIEWER_APPROVED"
    FINAL_RELEASED = "FINAL_RELEASED"
    GRADING_QUEUED = "GRADING_QUEUED"
    GRADING_FAILED = "GRADING_FAILED"


class SubmissionAnswerType(str, Enum):
    TEXT = "TEXT"
    SINGLE_OPTION = "SINGLE_OPTION"
    MULTI_OPTION = "MULTI_OPTION"
    ORDERED_LIST = "ORDERED_LIST"
    MATCH_PAIRS = "MATCH_PAIRS"
    FILL_BLANKS = "FILL_BLANKS"
    FILE = "FILE"


class AttemptStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    AUTO_SUBMITTED = "AUTO_SUBMITTED"
    ABANDONED = "ABANDONED"
    PENDING = "PENDING"
    PAUSED = "PAUSED"
    TIMED_OUT = "TIMED_OUT"
    FLAGGED = "FLAGGED"


class SubmissionGradingMode(str, Enum):
    AUTO = "AUTO"
    AI_SUGGESTED = "AI_SUGGESTED"
    LECTURER_MANUAL = "LECTURER_MANUAL"
    RUBRIC = "RUBRIC"
    AI_ASSISTED = "AI_ASSISTED"
    MANUAL = "MANUAL"
    HYBRID = "HYBRID"


class GradeStatus(str, Enum):
    PENDING = "PENDING"
    AUTO_GRADED = "AUTO_GRADED"
    AI_SUGGESTED = "AI_SUGGESTED"
    AWAITING_REVIEW = "AWAITING_REVIEW"
    LECTURER_REVIEWED = "LECTURER_REVIEWED"
    FINAL = "FINAL"
    RELEASED = "RELEASED"
    UNDER_APPEAL = "UNDER_APPEAL"


class GradingQueueStatus(str, Enum):
    PENDING = "PENDING"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class GradingQueuePriority(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"


class AppealStatus(str, Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    REVISED = "REVISED"
    WITHDRAWN = "WITHDRAWN"
    RESOLVED_UPHELD = "ACCEPTED"
    RESOLVED_REJECTED = "REJECTED"


class IntegrityEventType(str, Enum):
    FULLSCREEN_EXIT = "FULLSCREEN_EXIT"
    FULLSCREEN_ENTER = "FULLSCREEN_ENTER"
    TAB_SWITCH = "TAB_SWITCH"
    WINDOW_BLUR = "WINDOW_BLUR"
    WINDOW_FOCUS = "WINDOW_FOCUS"
    VISIBILITY_HIDDEN = "VISIBILITY_HIDDEN"
    COPY_ATTEMPT = "COPY_ATTEMPT"
    PASTE_ATTEMPT = "PASTE_ATTEMPT"
    RIGHT_CLICK = "RIGHT_CLICK"
    EXTENDED_INACTIVITY = "EXTENDED_INACTIVITY"
    RECONNECT = "RECONNECT"
    UNUSUAL_KEYPRESS = "UNUSUAL_KEYPRESS"


class RiskLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


IntegrityRiskLevel = RiskLevel


class WarningLevel(str, Enum):
    NONE = "NONE"
    WARNING_1 = "WARNING_1"
    WARNING_2 = "WARNING_2"
    WARNING_3 = "WARNING_3"


class SecurityEventType(str, Enum):
    FAILED_LOGIN = "FAILED_LOGIN"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    SUSPICIOUS_IP = "SUSPICIOUS_IP"
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
    ROLE_CHANGED = "ROLE_CHANGED"
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGIN_LOCKED = "LOGIN_LOCKED"
    LOGOUT = "LOGOUT"
    LOGOUT_ALL = "LOGOUT_ALL"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"
    TOKEN_THEFT_DETECTED = "TOKEN_THEFT_DETECTED"
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    ACCOUNT_REACTIVATED = "ACCOUNT_REACTIVATED"
    EMAIL_VERIFIED = "EMAIL_VERIFIED"
    VERIFICATION_EMAIL_RESENT = "VERIFICATION_EMAIL_RESENT"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED"
    SUSPICIOUS_LOGIN = "SUSPICIOUS_LOGIN"
    TAB_SWITCH = "TAB_SWITCH"
    FULLSCREEN_EXIT = "FULLSCREEN_EXIT"
    COPY_ATTEMPT = "COPY_ATTEMPT"
    PASTE_ATTEMPT = "PASTE_ATTEMPT"


class SecurityEventSeverity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    WARNING = "WARNING"


class NotificationChannel(str, Enum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    PUSH = "PUSH"
    BOTH = "BOTH"


class NotificationType(str, Enum):
    ASSESSMENT_PUBLISHED = "ASSESSMENT_PUBLISHED"
    ASSESSMENT_REMINDER = "ASSESSMENT_REMINDER"
    RESULT_RELEASED = "RESULT_RELEASED"
    FEEDBACK_RELEASED = "FEEDBACK_RELEASED"
    SUBMISSION_RECEIVED = "SUBMISSION_RECEIVED"
    GRADING_REQUIRED = "GRADING_REQUIRED"
    INTEGRITY_ALERT = "INTEGRITY_ALERT"
    APPEAL_SUBMITTED = "APPEAL_SUBMITTED"
    APPEAL_RESOLVED = "APPEAL_RESOLVED"
    DEADLINE_EXTENDED = "DEADLINE_EXTENDED"
    REASSESSMENT_SCHEDULED = "REASSESSMENT_SCHEDULED"
    ASSESSMENT_AVAILABLE = "ASSESSMENT_AVAILABLE"
    DEADLINE_REMINDER = "ASSESSMENT_REMINDER"
    GRADING_COMPLETE = "GRADING_REQUIRED"
    APPEAL_UPDATE = "APPEAL_RESOLVED"
    SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT"


class ScheduledEventType(str, Enum):
    ASSESSMENT_WINDOW_OPEN = "ASSESSMENT_WINDOW_OPEN"
    ASSESSMENT_DEADLINE = "ASSESSMENT_DEADLINE"
    RESULT_RELEASE = "RESULT_RELEASE"
    REASSESSMENT_WINDOW = "REASSESSMENT_WINDOW"
    REVIEW_DEADLINE = "REVIEW_DEADLINE"
    ASSESSMENT_WINDOW = "ASSESSMENT_WINDOW_OPEN"
    HOMEWORK_DEADLINE = "ASSESSMENT_DEADLINE"
    REVIEW_WINDOW = "REVIEW_DEADLINE"


class AIAgentType(str, Enum):
    ASSESSMENT_GENERATOR = "ASSESSMENT_GENERATOR"
    GRADING_ASSISTANT = "GRADING_ASSISTANT"
    STUDY_SUPPORT = "STUDY_SUPPORT"
    INTEGRITY_ANALYZER = "INTEGRITY_ANALYZER"


class AIOutputStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EDITED_AND_APPROVED = "EDITED_AND_APPROVED"


class ResultLetterGrade(str, Enum):
    A_PLUS = "A_PLUS"
    A = "A"
    A_MINUS = "A_MINUS"
    B_PLUS = "B_PLUS"
    B = "B"
    B_MINUS = "B_MINUS"
    C_PLUS = "C_PLUS"
    C = "C"
    C_MINUS = "C_MINUS"
    D = "D"
    F = "F"


class ResourceCategory(str, Enum):
    LECTURE_NOTES = "LECTURE_NOTES"
    PAST_PAPER = "PAST_PAPER"
    PERSONAL_NOTES = "PERSONAL_NOTES"
    OTHER = "OTHER"
    GENERAL = "GENERAL"
    TEXTBOOK_EXCERPT = "LECTURE_NOTES"
    ASSIGNMENT = "PAST_PAPER"


class ResourceProcessingStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    PROCESSING = "PENDING"
    COMPLETED = "PROCESSED"
    SKIPPED = "FAILED"


class IntegrityFlagStatus(str, Enum):
    OPEN = "OPEN"
    REVIEWED = "REVIEWED"
    DISMISSED = "DISMISSED"
    ESCALATED = "ESCALATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CONFIRMED = "CONFIRMED"


class IntegrityFlagRaisedBy(str, Enum):
    SYSTEM = "SYSTEM"
    SUPERVISOR = "SUPERVISOR"
    AI_AGENT = "AI_AGENT"
    ADMIN = "SUPERVISOR"


class SupervisionSessionStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ENDED = "ENDED"
