"""add ai target section parameters

Revision ID: 883ca7b6052b
Revises: 8c6ba2798b4b
Create Date: 2026-06-13 09:52:07.227212

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '883ca7b6052b'
down_revision: Union[str, None] = '8c6ba2798b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_generated_question', sa.Column('target_section_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_generated_question_target_section_id'), 'ai_generated_question', ['target_section_id'], unique=False)
    op.create_foreign_key(None, 'ai_generated_question', 'assessment_section', ['target_section_id'], ['id'], ondelete='SET NULL')
    op.add_column('ai_generation_batch', sa.Column('target_section_id', sa.UUID(), nullable=True))
    op.add_column('ai_generation_batch', sa.Column('sections_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_ai_generation_batch_target_section_id'), 'ai_generation_batch', ['target_section_id'], unique=False)
    op.create_foreign_key(None, 'ai_generation_batch', 'assessment_section', ['target_section_id'], ['id'], ondelete='SET NULL')
    op.alter_column('assessment', 'audience_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment', 'audience_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'all'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'ai_generation_batch', type_='foreignkey')
    op.drop_index(op.f('ix_ai_generation_batch_target_section_id'), table_name='ai_generation_batch')
    op.drop_column('ai_generation_batch', 'sections_json')
    op.drop_column('ai_generation_batch', 'target_section_id')
    op.drop_constraint(None, 'ai_generated_question', type_='foreignkey')
    op.drop_index(op.f('ix_ai_generated_question_target_section_id'), table_name='ai_generated_question')
    op.drop_column('ai_generated_question', 'target_section_id')
    # ### end Alembic commands ###
