"""add course_id to question

Revision ID: 78173997c983
Revises: d329660fdf3f
Create Date: 2026-06-05 12:50:01.721495

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '78173997c983'
down_revision: Union[str, None] = 'd329660fdf3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('question', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_question_course_id'), 'question', ['course_id'], unique=False)
    op.create_foreign_key(None, 'question', 'course', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_index(op.f('ix_question_course_id'), table_name='question')
    op.drop_column('question', 'image_url')
    op.drop_column('question', 'course_id')
    # ### end Alembic commands ###
