"""add_profile_fields_and_statuses

Revision ID: 6fe3243b818c
Revises: a76a168cf7e7
Create Date: 2026-04-30 12:33:49.051840

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '6fe3243b818c'
down_revision: Union[str, None] = 'a76a168cf7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('college', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('user_profile', sa.Column('option', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('user_profile', sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('user_profile', sa.Column('year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.drop_index('ix_user_profile_student_id', table_name='user_profile')
    op.create_index(op.f('ix_user_profile_student_id'), 'user_profile', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_student_id'), table_name='user_profile')
    op.create_index('ix_user_profile_student_id', 'user_profile', ['student_id'], unique=False)
    op.drop_column('user_profile', 'year')
    op.drop_column('user_profile', 'level')
    op.drop_column('user_profile', 'option')
    op.drop_column('user_profile', 'college')
    # ### end Alembic commands ###
