"""increase_academic_year_length

Revision ID: 277936c326b1
Revises: e64534d90434
Create Date: 2026-06-01 14:19:30.250259

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '277936c326b1'
down_revision: Union[str, None] = 'e64534d90434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment', 'academic_year',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('course', 'academic_year',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('teaching_assignment', 'academic_year',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teaching_assignment', 'academic_year',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('course', 'academic_year',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('assessment', 'academic_year',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
