"""add_provider_and_cost_to_ai_action_log

Revision ID: a598a12980a9
Revises: b427dd0a1c0e
Create Date: 2026-06-02 14:54:20.519425

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'a598a12980a9'
down_revision: Union[str, None] = 'b427dd0a1c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer_material_chunk',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lecturer_material_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('option_id', sa.Uuid(), nullable=True),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_material_id'], ['lecturer_material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lecturer_material_id', 'chunk_index', name='uq_lecturer_chunk_material_index')
    )
    op.create_index('ix_lecturer_material_chunk_course_id', 'lecturer_material_chunk', ['course_id'], unique=False)
    op.create_index('ix_lecturer_material_chunk_department_id', 'lecturer_material_chunk', ['department_id'], unique=False)
    op.create_index('ix_lecturer_material_chunk_embedding_model', 'lecturer_material_chunk', ['embedding_model'], unique=False)
    op.create_index('ix_lecturer_material_chunk_institution_id', 'lecturer_material_chunk', ['institution_id'], unique=False)
    op.create_index(op.f('ix_lecturer_material_chunk_is_deleted'), 'lecturer_material_chunk', ['is_deleted'], unique=False)
    op.create_index('ix_lecturer_material_chunk_lecturer_material_id_chunk_index', 'lecturer_material_chunk', ['lecturer_material_id', 'chunk_index'], unique=False)
    op.add_column('ai_action_log', sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('ai_action_log', sa.Column('cost_estimate', sa.Float(), nullable=True))
    op.add_column('lecturer_material', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.add_column('lecturer_material', sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='resourceprocessingstatus'), nullable=False))
    op.add_column('lecturer_material', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('lecturer_material', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    op.add_column('lecturer_material', sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('lecturer_material', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.create_index('ix_lecturer_material_processing_status', 'lecturer_material', ['processing_status'], unique=False)
    op.create_foreign_key(None, 'lecturer_material', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.add_column('resource_chunk', sa.Column('student_id', sa.Uuid(), nullable=False))
    op.add_column('resource_chunk', sa.Column('institution_id', sa.Uuid(), nullable=True))
    op.create_index('ix_resource_chunk_institution_id', 'resource_chunk', ['institution_id'], unique=False)
    op.create_index('ix_resource_chunk_student_id', 'resource_chunk', ['student_id'], unique=False)
    op.add_column('submission_grade', sa.Column('ai_feedback_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('submission_grade', sa.Column('ai_feedback_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission_grade', sa.Column('ai_feedback_improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission_grade', sa.Column('ai_feedback_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_grade', 'ai_feedback_suggestions')
    op.drop_column('submission_grade', 'ai_feedback_improvements')
    op.drop_column('submission_grade', 'ai_feedback_strengths')
    op.drop_column('submission_grade', 'ai_feedback_draft')
    op.drop_index('ix_resource_chunk_student_id', table_name='resource_chunk')
    op.drop_index('ix_resource_chunk_institution_id', table_name='resource_chunk')
    op.drop_column('resource_chunk', 'institution_id')
    op.drop_column('resource_chunk', 'student_id')
    op.drop_constraint(None, 'lecturer_material', type_='foreignkey')
    op.drop_index('ix_lecturer_material_processing_status', table_name='lecturer_material')
    op.drop_column('lecturer_material', 'chunk_count')
    op.drop_column('lecturer_material', 'processing_error')
    op.drop_column('lecturer_material', 'processing_completed_at')
    op.drop_column('lecturer_material', 'processing_started_at')
    op.drop_column('lecturer_material', 'processing_status')
    op.drop_column('lecturer_material', 'institution_id')
    op.drop_column('ai_action_log', 'cost_estimate')
    op.drop_column('ai_action_log', 'provider_name')
    op.drop_index('ix_lecturer_material_chunk_lecturer_material_id_chunk_index', table_name='lecturer_material_chunk')
    op.drop_index(op.f('ix_lecturer_material_chunk_is_deleted'), table_name='lecturer_material_chunk')
    op.drop_index('ix_lecturer_material_chunk_institution_id', table_name='lecturer_material_chunk')
    op.drop_index('ix_lecturer_material_chunk_embedding_model', table_name='lecturer_material_chunk')
    op.drop_index('ix_lecturer_material_chunk_department_id', table_name='lecturer_material_chunk')
    op.drop_index('ix_lecturer_material_chunk_course_id', table_name='lecturer_material_chunk')
    op.drop_table('lecturer_material_chunk')
    # ### end Alembic commands ###
