"""update_vector_dimensions_for_jina

Revision ID: c5e08d04f88b
Revises: a598a12980a9
Create Date: 2026-06-02 19:57:02.810854

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic
revision: str = 'c5e08d04f88b'
down_revision: Union[str, None] = 'a598a12980a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
