"""add_ai_grading_audit_fields_to_submission_grade

Revision ID: e7029ae23c0b
Revises: 05fd37907751
Create Date: 2026-07-17 20:45:09.928752

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'e7029ae23c0b'
down_revision: Union[str, None] = '05fd37907751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_grade', sa.Column('ai_grading_basis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('submission_grade', sa.Column('ai_context_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission_grade', sa.Column('rag_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission_grade', sa.Column('rubric_id_used', sa.UUID(), nullable=True))
    op.add_column('submission_grade', sa.Column('fallback_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('submission_grade', sa.Column('rag_used', sa.Boolean(), nullable=True))
    op.add_column('submission_grade', sa.Column('rag_source_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission_grade', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('submission_grade', sa.Column('tokens', sa.Integer(), nullable=True))
    op.add_column('submission_grade', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('submission_grade', sa.Column('ai_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('submission_grade', sa.Column('ai_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_grade', 'ai_completed_at')
    op.drop_column('submission_grade', 'ai_started_at')
    op.drop_column('submission_grade', 'cost')
    op.drop_column('submission_grade', 'tokens')
    op.drop_column('submission_grade', 'model')
    op.drop_column('submission_grade', 'rag_source_labels')
    op.drop_column('submission_grade', 'rag_used')
    op.drop_column('submission_grade', 'fallback_reason')
    op.drop_column('submission_grade', 'rubric_id_used')
    op.drop_column('submission_grade', 'rag_chunk_ids')
    op.drop_column('submission_grade', 'ai_context_sources')
    op.drop_column('submission_grade', 'ai_grading_basis')
    # ### end Alembic commands ###
