"""add_group_work_metadata_fields

Revision ID: ab76d35727d4
Revises: 43a7d2eedf5d
Create Date: 2026-07-04 23:00:45.808193

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'ab76d35727d4'
down_revision: Union[str, None] = '43a7d2eedf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_generated_question', 'grounded_by_rag',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('assessment', sa.Column('submission_mode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('assessment', sa.Column('peer_evaluation_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('assessment', sa.Column('peer_evaluation_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessment', sa.Column('peer_evaluation_weight_percent', sa.Integer(), nullable=True))
    op.add_column('assessment', sa.Column('individual_weighting_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('result_breakdown', 'feedback_author_basis',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('submission_grade', 'feedback_author_basis',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission_grade', 'feedback_author_basis',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'LECTURER'::character varying"),
               nullable=True)
    op.alter_column('result_breakdown', 'feedback_author_basis',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'LECTURER'::character varying"),
               existing_nullable=True)
    op.drop_column('assessment', 'individual_weighting_enabled')
    op.drop_column('assessment', 'peer_evaluation_weight_percent')
    op.drop_column('assessment', 'peer_evaluation_deadline')
    op.drop_column('assessment', 'peer_evaluation_enabled')
    op.drop_column('assessment', 'submission_mode')
    op.alter_column('ai_generated_question', 'grounded_by_rag',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
