"""add_resource_category_to_academic_resource

Revision ID: 8d28b1ec0641
Revises: 4a703d518af9
Create Date: 2026-06-16 08:47:16.832464

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '8d28b1ec0641'
down_revision: Union[str, None] = '4a703d518af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_resources', sa.Column('resource_category', sa.Enum('LECTURE_NOTES', 'PAST_PAPER', 'PERSONAL_NOTES', 'QUESTION_BANK', 'ANSWER_KEY', 'OTHER', 'GENERAL', name='resourcecategory'), nullable=False))
    op.drop_index('resource_chunks_embedding_idx', table_name='resource_chunks', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('resource_chunks_embedding_idx', 'resource_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_column('academic_resources', 'resource_category')
    # ### end Alembic commands ###
