"""add_student_targeting_fields

Revision ID: 8c6ba2798b4b
Revises: e968e541c2a0
Create Date: 2026-06-12 13:14:27.514738

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '8c6ba2798b4b'
down_revision: Union[str, None] = 'e968e541c2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('student_enrollment_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('assessment', sa.Column('audience_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='all'))
    op.add_column('assessment', sa.Column('target_student_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'target_student_ids')
    op.drop_column('assessment', 'audience_type')
    op.drop_column('assessment', 'student_enrollment_snapshot')
    # ### end Alembic commands ###
