"""implement_teaching_workspaces

Revision ID: 9a273e2ef00a
Revises: 92944c2dcf67
Create Date: 2026-05-23 16:35:29.488632

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '9a273e2ef00a'
down_revision: Union[str, None] = '92944c2dcf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_workspace',
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('teaching_assignment_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('class_section_id', sa.UUID(), nullable=False),
    sa.Column('academic_period_id', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_assignment_id'], ['teaching_assignment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_workspace_created_by_id'), 'teaching_workspace', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_teaching_workspace_is_deleted'), 'teaching_workspace', ['is_deleted'], unique=False)
    op.add_column('assessment', sa.Column('teaching_workspace_id', sa.UUID(), nullable=False))
    op.alter_column('assessment', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_assessment_course_id_assessment_type'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_course_id_status'), table_name='assessment')
    op.create_index('ix_assessment_teaching_workspace_id_assessment_type', 'assessment', ['teaching_workspace_id', 'assessment_type'], unique=False)
    op.create_index('ix_assessment_teaching_workspace_id_status', 'assessment', ['teaching_workspace_id', 'status'], unique=False)
    op.create_foreign_key(None, 'assessment', 'teaching_workspace', ['teaching_workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('lecturer_material', sa.Column('teaching_workspace_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_lecturer_material_course_id_is_current'), table_name='lecturer_material')
    op.drop_index(op.f('ix_lecturer_material_course_id_is_student_visible'), table_name='lecturer_material')
    op.create_index('ix_lecturer_material_teaching_workspace_id_is_current', 'lecturer_material', ['teaching_workspace_id', 'is_current'], unique=False)
    op.create_index('ix_lecturer_material_teaching_workspace_id_is_student_visible', 'lecturer_material', ['teaching_workspace_id', 'is_student_visible'], unique=False)
    op.create_foreign_key(None, 'lecturer_material', 'teaching_workspace', ['teaching_workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('subject', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('subject', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.alter_column('subject', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_subject_department_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_institution_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_title'), table_name='subject')
    op.drop_constraint(op.f('uq_subject_inst_title'), 'subject', type_='unique')
    op.create_unique_constraint('uq_subject_dept_code', 'subject', ['department_id', 'code'])
    op.drop_constraint(op.f('subject_department_id_fkey'), 'subject', type_='foreignkey')
    op.drop_constraint(op.f('subject_institution_id_fkey'), 'subject', type_='foreignkey')
    op.create_foreign_key(None, 'subject', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subject', 'description')
    op.drop_column('subject', 'title')
    op.drop_column('subject', 'institution_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('institution_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('subject', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('subject', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.create_foreign_key(op.f('subject_institution_id_fkey'), 'subject', 'institution', ['institution_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('subject_department_id_fkey'), 'subject', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_subject_dept_code', 'subject', type_='unique')
    op.create_unique_constraint(op.f('uq_subject_inst_title'), 'subject', ['institution_id', 'title'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_subject_title'), 'subject', ['title'], unique=False)
    op.create_index(op.f('ix_subject_institution_id'), 'subject', ['institution_id'], unique=False)
    op.create_index(op.f('ix_subject_department_id'), 'subject', ['department_id'], unique=False)
    op.alter_column('subject', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('subject', 'code')
    op.drop_column('subject', 'name')
    op.drop_constraint(None, 'lecturer_material', type_='foreignkey')
    op.drop_index('ix_lecturer_material_teaching_workspace_id_is_student_visible', table_name='lecturer_material')
    op.drop_index('ix_lecturer_material_teaching_workspace_id_is_current', table_name='lecturer_material')
    op.create_index(op.f('ix_lecturer_material_course_id_is_student_visible'), 'lecturer_material', ['course_id', 'is_student_visible'], unique=False)
    op.create_index(op.f('ix_lecturer_material_course_id_is_current'), 'lecturer_material', ['course_id', 'is_current'], unique=False)
    op.drop_column('lecturer_material', 'teaching_workspace_id')
    op.drop_constraint(None, 'assessment', type_='foreignkey')
    op.drop_index('ix_assessment_teaching_workspace_id_status', table_name='assessment')
    op.drop_index('ix_assessment_teaching_workspace_id_assessment_type', table_name='assessment')
    op.create_index(op.f('ix_assessment_course_id_status'), 'assessment', ['course_id', 'status'], unique=False)
    op.create_index(op.f('ix_assessment_course_id_assessment_type'), 'assessment', ['course_id', 'assessment_type'], unique=False)
    op.alter_column('assessment', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('assessment', 'teaching_workspace_id')
    op.drop_index(op.f('ix_teaching_workspace_is_deleted'), table_name='teaching_workspace')
    op.drop_index(op.f('ix_teaching_workspace_created_by_id'), table_name='teaching_workspace')
    op.drop_table('teaching_workspace')
    # ### end Alembic commands ###
