"""add_promoted_question_id_to_ai_generated_question

Revision ID: f11032db97ba
Revises: 10c9a46e8373
Create Date: 2026-06-19 09:36:27.467478

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'f11032db97ba'
down_revision: Union[str, None] = '10c9a46e8373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_generated_question', sa.Column('promoted_question_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ai_generated_question', 'question', ['promoted_question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_generated_question', type_='foreignkey')
    op.drop_column('ai_generated_question', 'promoted_question_id')
    # ### end Alembic commands ###
