"""make_college_belong_to_institution_directly

Revision ID: e64534d90434
Revises: f0218415386f
Create Date: 2026-06-01 10:25:56.104426

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'e64534d90434'
down_revision: Union[str, None] = 'f0218415386f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college', sa.Column('institution_id', sa.UUID(), nullable=True))
    
    # Data migration: populate institution_id from campus_id
    op.execute("UPDATE college SET institution_id = campus.institution_id FROM campus WHERE college.campus_id = campus.id")
    
    op.alter_column('college', 'institution_id', nullable=False)
    op.alter_column('college', 'campus_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_college_campus_id', table_name='college')
    op.drop_constraint('uq_college_campus_code', 'college', type_='unique')
    op.create_index('ix_college_institution_id', 'college', ['institution_id'], unique=False)
    op.create_unique_constraint('uq_college_inst_code', 'college', ['institution_id', 'code'])
    op.drop_constraint('college_campus_id_fkey', 'college', type_='foreignkey')
    op.create_foreign_key(None, 'college', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'college', 'campus', ['campus_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'college', type_='foreignkey')
    op.drop_constraint(None, 'college', type_='foreignkey')
    op.create_foreign_key('college_campus_id_fkey', 'college', 'campus', ['campus_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_college_inst_code', 'college', type_='unique')
    op.drop_index('ix_college_institution_id', table_name='college')
    op.create_unique_constraint('uq_college_campus_code', 'college', ['campus_id', 'code'])
    op.create_index('ix_college_campus_id', 'college', ['campus_id'], unique=False)
    op.alter_column('college', 'campus_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('college', 'institution_id')
    # ### end Alembic commands ###
