"""add_rag_blueprint_fields_to_ai_generation_batch

Revision ID: 10c9a46e8373
Revises: 450db1fdd7c4
Create Date: 2026-06-18 07:30:47.223663

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '10c9a46e8373'
down_revision: Union[str, None] = '450db1fdd7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_generation_batch', sa.Column('teaching_workspace_id', sa.UUID(), nullable=True))
    op.add_column('ai_generation_batch', sa.Column('blueprint_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ai_generation_batch', sa.Column('learning_outcomes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ai_generation_batch', sa.Column('marks_per_question', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ai_generation_batch_teaching_workspace_id'), 'ai_generation_batch', ['teaching_workspace_id'], unique=False)
    op.create_foreign_key(None, 'ai_generation_batch', 'teaching_workspace', ['teaching_workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_generation_batch', type_='foreignkey')
    op.drop_index(op.f('ix_ai_generation_batch_teaching_workspace_id'), table_name='ai_generation_batch')
    op.drop_column('ai_generation_batch', 'marks_per_question')
    op.drop_column('ai_generation_batch', 'learning_outcomes')
    op.drop_column('ai_generation_batch', 'blueprint_constraints')
    op.drop_column('ai_generation_batch', 'teaching_workspace_id')
    # ### end Alembic commands ###
