"""refactor_class_section_final

Revision ID: e2127a6a795c
Revises: eecf2d2063ae
Create Date: 2026-06-03 22:43:34.607782

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'e2127a6a795c'
down_revision: Union[str, None] = 'eecf2d2063ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    location_type_enum = sa.Enum('PHYSICAL_ROOM', 'ONLINE', 'HYBRID', 'NOT_APPLICABLE', name='locationtype')
    location_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('class_section', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('class_section', sa.Column('location_type', location_type_enum, server_default='PHYSICAL_ROOM', nullable=False))
    
    # Safely drop constraints and indexes that might not exist or use auto-names
    # Depending on previous migrations/db state
    try:
        op.drop_index('ix_class_section_course_id_is_active', table_name='class_section')
    except: pass
    
    try:
        op.drop_constraint('uq_class_section_course_name', 'class_section', type_='unique')
    except: pass

    op.create_index('ix_class_section_class_group_id_is_active', 'class_section', ['class_group_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_class_section_department_id'), 'class_section', ['department_id'], unique=False)
    op.create_unique_constraint('uq_class_section_group_name', 'class_section', ['class_group_id', 'name'])
    
    try:
        op.drop_constraint('class_section_course_id_fkey', 'class_section', type_='foreignkey')
    except: pass
        
    op.create_foreign_key(None, 'class_section', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('class_section', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_section', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'class_section', type_='foreignkey')
    op.create_foreign_key('class_section_course_id_fkey', 'class_section', 'course', ['course_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_class_section_group_name', 'class_section', type_='unique')
    op.drop_index(op.f('ix_class_section_department_id'), table_name='class_section')
    op.drop_index('ix_class_section_class_group_id_is_active', table_name='class_section')
    op.create_unique_constraint('uq_class_section_course_name', 'class_section', ['course_id', 'name'])
    op.create_index('ix_class_section_course_id_is_active', 'class_section', ['course_id', 'is_active'], unique=False)
    op.drop_column('class_section', 'location_type')
    op.drop_column('class_section', 'department_id')
    # ### end Alembic commands ###
