"""update_assessment_target_section_audit

Revision ID: 1e4c66fe4db2
Revises: 168ede9302c8
Create Date: 2026-05-15 14:26:44.998069

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '1e4c66fe4db2'
down_revision: Union[str, None] = '168ede9302c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'target_class')
    op.drop_column('assessment', 'subject')
    op.add_column('assessment_target_section', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.add_column('assessment_target_section', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_assessment_target_section_created_by_id'), 'assessment_target_section', ['created_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_target_section_created_by_id'), table_name='assessment_target_section')
    op.drop_column('assessment_target_section', 'updated_by_id')
    op.drop_column('assessment_target_section', 'created_by_id')
    op.add_column('assessment', sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('assessment', sa.Column('target_class', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
