"""add_integrity_profile_and_assessment_integrity_fields

Revision ID: 0a02e34b2c47
Revises: e7029ae23c0b
Create Date: 2026-07-28 00:45:43.326989

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '0a02e34b2c47'
down_revision: Union[str, None] = 'e7029ae23c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrity_profile',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('allow_resume', sa.Boolean(), nullable=False),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrity_profile_code'), 'integrity_profile', ['code'], unique=True)
    op.create_index(op.f('ix_integrity_profile_is_deleted'), 'integrity_profile', ['is_deleted'], unique=False)
    op.add_column('assessment', sa.Column('allow_resume', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('assessment', sa.Column('integrity_profile_id', sa.UUID(), nullable=True))
    op.add_column('assessment', sa.Column('integrity_policy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'assessment', 'integrity_profile', ['integrity_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessment', type_='foreignkey')
    op.drop_column('assessment', 'integrity_policy_json')
    op.drop_column('assessment', 'integrity_profile_id')
    op.drop_column('assessment', 'allow_resume')
    op.drop_index(op.f('ix_integrity_profile_is_deleted'), table_name='integrity_profile')
    op.drop_index(op.f('ix_integrity_profile_code'), table_name='integrity_profile')
    op.drop_table('integrity_profile')
    # ### end Alembic commands ###
