"""rename_marks_allocated_to_allocated_marks

Revision ID: 21fa16226673
Revises: 6fe3243b818c
Create Date: 2026-05-02 11:04:46.681115

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '21fa16226673'
down_revision: Union[str, None] = '6fe3243b818c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_section', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('assessment_section', 'marks_allocated', new_column_name='allocated_marks')
    # op.drop_index(op.f('ix_result_appeal_student_id'), table_name='result_appeal')
    # op.drop_index(op.f('ix_submission_grade_student_id'), table_name='submission_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_submission_grade_student_id'), 'submission_grade', ['student_id'], unique=False)
    # op.create_index(op.f('ix_result_appeal_student_id'), 'result_appeal', ['student_id'], unique=False)
    op.alter_column('assessment_section', 'allocated_marks', new_column_name='marks_allocated')
    op.drop_column('assessment_section', 'description')
    # ### end Alembic commands ###
