"""sync_missing_tables

Revision ID: 6071322c9457
Revises: c224a53175be
Create Date: 2026-05-23 11:01:01.224303

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '6071322c9457'
down_revision: Union[str, None] = 'c224a53175be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_campus_inst_code')
    )
    op.create_index('ix_campus_institution_id', 'campus', ['institution_id'], unique=False)
    op.create_index(op.f('ix_campus_is_deleted'), 'campus', ['is_deleted'], unique=False)
    op.create_table('college',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'code', name='uq_college_campus_code')
    )
    op.create_index('ix_college_campus_id', 'college', ['campus_id'], unique=False)
    op.create_index(op.f('ix_college_is_deleted'), 'college', ['is_deleted'], unique=False)
    op.create_table('teaching_assignment',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=True),
    sa.Column('college_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('class_section_id', sa.UUID(), nullable=True),
    sa.Column('academic_period_id', sa.UUID(), nullable=True),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_section.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_assignment_external_id'), 'teaching_assignment', ['external_id'], unique=False)
    op.create_index(op.f('ix_teaching_assignment_is_deleted'), 'teaching_assignment', ['is_deleted'], unique=False)
    op.add_column('assessment', sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.drop_index(op.f('ix_assessment_attempt_group_id'), table_name='assessment_attempt')
    op.add_column('course', sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.alter_column('course', 'academic_period_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('department', sa.Column('campus_id', sa.UUID(), nullable=True))
    op.add_column('department', sa.Column('college_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'department', 'college', ['college_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'department', 'campus', ['campus_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_grading_queue_item_assessment_id'), table_name='grading_queue_item')
    op.drop_index(op.f('ix_grading_queue_item_assigned_to_id'), table_name='grading_queue_item')
    op.drop_index(op.f('ix_grading_queue_item_attempt_id'), table_name='grading_queue_item')
    op.drop_index(op.f('ix_grading_queue_item_question_id'), table_name='grading_queue_item')
    op.drop_index(op.f('ix_grading_queue_item_response_id'), table_name='grading_queue_item')
    op.drop_index(op.f('ix_grading_queue_item_student_id'), table_name='grading_queue_item')
    op.drop_index(op.f('ix_group_activity_log_question_id'), table_name='group_activity_log')
    op.drop_index(op.f('ix_group_activity_log_student_id'), table_name='group_activity_log')
    op.drop_index(op.f('ix_group_activity_log_submission_id'), table_name='group_activity_log')
    op.alter_column('group_appeal', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('group_appeal', 'statement',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_group_appeal_initiated_by_id'), table_name='group_appeal')
    op.drop_index(op.f('ix_group_appeal_submission_id'), table_name='group_appeal')
    op.alter_column('group_appeal_approval', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_group_appeal_approval_appeal_id'), table_name='group_appeal_approval')
    op.drop_index(op.f('ix_group_appeal_approval_student_id'), table_name='group_appeal_approval')
    op.alter_column('group_assessment_material', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('group_assessment_material', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('group_assessment_material', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('group_submission', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('group_submission', 'feedback',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_group_submission_assessment_id'), table_name='group_submission')
    op.drop_index(op.f('ix_group_submission_group_id'), table_name='group_submission')
    op.alter_column('group_submission_answer', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('group_submission_approval', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_group_submission_approval_student_id'), table_name='group_submission_approval')
    op.drop_index(op.f('ix_group_submission_approval_submission_id'), table_name='group_submission_approval')
    op.alter_column('group_submission_comment', 'body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_group_submission_comment_author_id'), table_name='group_submission_comment')
    op.drop_index(op.f('ix_group_submission_comment_question_id'), table_name='group_submission_comment')
    op.drop_index(op.f('ix_group_submission_comment_submission_id'), table_name='group_submission_comment')
    op.drop_index(op.f('ix_result_appeal_assessment_id'), table_name='result_appeal')
    op.drop_index(op.f('ix_result_appeal_reviewer_id'), table_name='result_appeal')
    op.drop_index(op.f('ix_result_appeal_submission_grade_id'), table_name='result_appeal')
    op.drop_index(op.f('ix_rubric_grade_selected_level_id'), table_name='rubric_grade')
    op.drop_index(op.f('ix_student_group_assessment_id'), table_name='student_group')
    op.drop_index(op.f('ix_student_response_attempt_id'), table_name='student_response')
    op.drop_index(op.f('ix_student_response_question_id'), table_name='student_response')
    op.drop_index(op.f('ix_student_response_log_attempt_id'), table_name='student_response_log')
    op.drop_index(op.f('ix_student_response_log_question_id'), table_name='student_response_log')
    op.drop_index(op.f('ix_student_response_log_response_id'), table_name='student_response_log')
    op.drop_index(op.f('ix_submission_grade_assessment_id'), table_name='submission_grade')
    op.drop_index(op.f('ix_submission_grade_attempt_id'), table_name='submission_grade')
    op.drop_index(op.f('ix_submission_grade_question_id'), table_name='submission_grade')
    op.drop_index(op.f('ix_submission_grade_response_id'), table_name='submission_grade')
    op.add_column('user_profile', sa.Column('campus_id', sa.UUID(), nullable=True))
    op.add_column('user_profile', sa.Column('college_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_profile_campus_id'), 'user_profile', ['campus_id'], unique=False)
    op.create_index(op.f('ix_user_profile_college_id'), 'user_profile', ['college_id'], unique=False)
    op.create_foreign_key(None, 'user_profile', 'campus', ['campus_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_profile', 'college', ['college_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_index(op.f('ix_user_profile_college_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_campus_id'), table_name='user_profile')
    op.drop_column('user_profile', 'college_id')
    op.drop_column('user_profile', 'campus_id')
    op.create_index(op.f('ix_submission_grade_response_id'), 'submission_grade', ['response_id'], unique=False)
    op.create_index(op.f('ix_submission_grade_question_id'), 'submission_grade', ['question_id'], unique=False)
    op.create_index(op.f('ix_submission_grade_attempt_id'), 'submission_grade', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_submission_grade_assessment_id'), 'submission_grade', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_student_response_log_response_id'), 'student_response_log', ['response_id'], unique=False)
    op.create_index(op.f('ix_student_response_log_question_id'), 'student_response_log', ['question_id'], unique=False)
    op.create_index(op.f('ix_student_response_log_attempt_id'), 'student_response_log', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_student_response_question_id'), 'student_response', ['question_id'], unique=False)
    op.create_index(op.f('ix_student_response_attempt_id'), 'student_response', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_student_group_assessment_id'), 'student_group', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_rubric_grade_selected_level_id'), 'rubric_grade', ['selected_level_id'], unique=False)
    op.create_index(op.f('ix_result_appeal_submission_grade_id'), 'result_appeal', ['submission_grade_id'], unique=False)
    op.create_index(op.f('ix_result_appeal_reviewer_id'), 'result_appeal', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_result_appeal_assessment_id'), 'result_appeal', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_group_submission_comment_submission_id'), 'group_submission_comment', ['submission_id'], unique=False)
    op.create_index(op.f('ix_group_submission_comment_question_id'), 'group_submission_comment', ['question_id'], unique=False)
    op.create_index(op.f('ix_group_submission_comment_author_id'), 'group_submission_comment', ['author_id'], unique=False)
    op.alter_column('group_submission_comment', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_group_submission_approval_submission_id'), 'group_submission_approval', ['submission_id'], unique=False)
    op.create_index(op.f('ix_group_submission_approval_student_id'), 'group_submission_approval', ['student_id'], unique=False)
    op.alter_column('group_submission_approval', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('group_submission_answer', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('ix_group_submission_group_id'), 'group_submission', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_submission_assessment_id'), 'group_submission', ['assessment_id'], unique=False)
    op.alter_column('group_submission', 'feedback',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('group_submission', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('group_assessment_material', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('group_assessment_material', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('group_assessment_material', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('ix_group_appeal_approval_student_id'), 'group_appeal_approval', ['student_id'], unique=False)
    op.create_index(op.f('ix_group_appeal_approval_appeal_id'), 'group_appeal_approval', ['appeal_id'], unique=False)
    op.alter_column('group_appeal_approval', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('ix_group_appeal_submission_id'), 'group_appeal', ['submission_id'], unique=False)
    op.create_index(op.f('ix_group_appeal_initiated_by_id'), 'group_appeal', ['initiated_by_id'], unique=False)
    op.alter_column('group_appeal', 'statement',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('group_appeal', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('ix_group_activity_log_submission_id'), 'group_activity_log', ['submission_id'], unique=False)
    op.create_index(op.f('ix_group_activity_log_student_id'), 'group_activity_log', ['student_id'], unique=False)
    op.create_index(op.f('ix_group_activity_log_question_id'), 'group_activity_log', ['question_id'], unique=False)
    op.create_index(op.f('ix_grading_queue_item_student_id'), 'grading_queue_item', ['student_id'], unique=False)
    op.create_index(op.f('ix_grading_queue_item_response_id'), 'grading_queue_item', ['response_id'], unique=False)
    op.create_index(op.f('ix_grading_queue_item_question_id'), 'grading_queue_item', ['question_id'], unique=False)
    op.create_index(op.f('ix_grading_queue_item_attempt_id'), 'grading_queue_item', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_grading_queue_item_assigned_to_id'), 'grading_queue_item', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_grading_queue_item_assessment_id'), 'grading_queue_item', ['assessment_id'], unique=False)
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'college_id')
    op.drop_column('department', 'campus_id')
    op.alter_column('course', 'academic_period_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('course', 'academic_year')
    op.create_index(op.f('ix_assessment_attempt_group_id'), 'assessment_attempt', ['group_id'], unique=False)
    op.drop_column('assessment', 'academic_year')
    op.drop_index(op.f('ix_teaching_assignment_is_deleted'), table_name='teaching_assignment')
    op.drop_index(op.f('ix_teaching_assignment_external_id'), table_name='teaching_assignment')
    op.drop_table('teaching_assignment')
    op.drop_index(op.f('ix_college_is_deleted'), table_name='college')
    op.drop_index('ix_college_campus_id', table_name='college')
    op.drop_table('college')
    op.drop_index(op.f('ix_campus_is_deleted'), table_name='campus')
    op.drop_index('ix_campus_institution_id', table_name='campus')
    op.drop_table('campus')
    # ### end Alembic commands ###
