"""add_group_configuration_to_assessment

Revision ID: 4149728e9d5c
Revises: 21fa16226673
Create Date: 2026-05-03 19:04:38.483821

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '4149728e9d5c'
down_revision: Union[str, None] = '21fa16226673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('max_group_size', sa.Integer(), nullable=True))
    op.add_column('assessment', sa.Column('group_formation_mode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.alter_column('assessment', 'is_supervised',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_result_appeal_student_id', table_name='result_appeal')
    op.drop_index('ix_submission_grade_student_id', table_name='submission_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_submission_grade_student_id', 'submission_grade', ['student_id'], unique=False)
    op.create_index('ix_result_appeal_student_id', 'result_appeal', ['student_id'], unique=False)
    op.alter_column('assessment', 'is_supervised',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('assessment', 'group_formation_mode')
    op.drop_column('assessment', 'max_group_size')
    # ### end Alembic commands ###
