"""refactor_class_section_v5_final_structure

Revision ID: 35747f0afc1c
Revises: e2127a6a795c
Create Date: 2026-06-03 23:39:10.518290

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '35747f0afc1c'
down_revision: Union[str, None] = 'e2127a6a795c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create Enums if they don't exist
    section_status_enum = sa.Enum('ACTIVE', 'ARCHIVED', 'GRADUATED', 'SUSPENDED', name='classsectionstatus')
    section_status_enum.create(op.get_bind(), checkfirst=True)

    # 2. Add columns to class_section
    op.add_column('class_section', sa.Column('academic_year', sa.String(length=100), nullable=True))
    op.add_column('class_section', sa.Column('status', section_status_enum, server_default='ACTIVE', nullable=False))
    
    # Update existing rows with a placeholder year before making it non-nullable
    op.execute("UPDATE class_section SET academic_year = '2026' WHERE academic_year IS NULL")
    op.alter_column('class_section', 'academic_year', nullable=False)

    # 3. Handle Constraints
    # Drop old index and constraint
    try:
        op.drop_index('ix_class_section_class_group_id_is_active', table_name='class_section')
    except: pass
    
    try:
        op.drop_constraint('uq_class_section_group_name', 'class_section', type_='unique')
    except: pass

    # Create new scoped constraint including academic_year
    op.create_unique_constraint('uq_class_section_scope_year', 'class_section', ['class_group_id', 'name', 'academic_year'])
    op.create_index('ix_class_section_class_group_id_is_active', 'class_section', ['class_group_id', 'is_active'], unique=False)

    # 4. Lecturer Course Assignment (Shared Teaching)
    # Drop old version if it exists (it might have been created by initial_schema)
    op.execute("DROP TABLE IF EXISTS lecturer_course_assignment CASCADE")
    
    op.create_table('lecturer_course_assignment',
        sa.Column('lecturer_id', sa.UUID(), nullable=False),
        sa.Column('course_id', sa.UUID(), nullable=False),
        sa.Column('assignment_role', sa.String(length=50), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
        sa.ForeignKeyConstraint(['lecturer_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('lecturer_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturer_course_assignment')
    op.drop_index('ix_class_section_class_group_id_is_active', table_name='class_section')
    op.drop_constraint('uq_class_section_scope_year', 'class_section', type_='unique')
    op.create_unique_constraint('uq_class_section_group_name', 'class_section', ['class_group_id', 'name'])
    op.create_index('ix_class_section_class_group_id_is_active', 'class_section', ['class_group_id', 'is_active'], unique=False)
    op.drop_column('class_section', 'status')
    op.drop_column('class_section', 'academic_year')
    # ### end Alembic commands ###
