"""add_structured_academic_hierarchy

Revision ID: 168ede9302c8
Revises: 4149728e9d5c
Create Date: 2026-05-15 11:44:30.639384

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '168ede9302c8'
down_revision: Union[str, None] = '4149728e9d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer_institution',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'lecturer_id', 'institution_id')
    )
    op.create_index(op.f('ix_lecturer_institution_is_deleted'), 'lecturer_institution', ['is_deleted'], unique=False)
    op.create_table('lecturer_department',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'lecturer_id', 'department_id')
    )
    op.create_index(op.f('ix_lecturer_department_is_deleted'), 'lecturer_department', ['is_deleted'], unique=False)
    op.create_table('option',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_option_dept_code')
    )
    op.create_index('ix_option_department_id', 'option', ['department_id'], unique=False)
    op.create_index(op.f('ix_option_is_active'), 'option', ['is_active'], unique=False)
    op.create_index(op.f('ix_option_is_deleted'), 'option', ['is_deleted'], unique=False)
    op.create_table('class_group',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'code', name='uq_class_group_option_code')
    )
    op.create_index(op.f('ix_class_group_is_active'), 'class_group', ['is_active'], unique=False)
    op.create_index(op.f('ix_class_group_is_deleted'), 'class_group', ['is_deleted'], unique=False)
    op.create_index('ix_class_group_option_id', 'class_group', ['option_id'], unique=False)
    op.create_table('course_department',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'course_id', 'department_id')
    )
    op.create_index(op.f('ix_course_department_is_deleted'), 'course_department', ['is_deleted'], unique=False)
    op.create_table('course_option',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'course_id', 'option_id')
    )
    op.create_index(op.f('ix_course_option_is_deleted'), 'course_option', ['is_deleted'], unique=False)
    op.create_table('lecturer_option',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'lecturer_id', 'option_id')
    )
    op.create_index(op.f('ix_lecturer_option_is_deleted'), 'lecturer_option', ['is_deleted'], unique=False)
    op.add_column('class_section', sa.Column('class_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_class_section_class_group_id'), 'class_section', ['class_group_id'], unique=False)
    op.create_foreign_key(None, 'class_section', 'class_group', ['class_group_id'], ['id'], ondelete='SET NULL')
    op.add_column('course', sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('course', sa.Column('option_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'option_name')
    op.drop_column('course', 'department_name')
    op.drop_constraint(None, 'class_section', type_='foreignkey')
    op.drop_index(op.f('ix_class_section_class_group_id'), table_name='class_section')
    op.drop_column('class_section', 'class_group_id')
    op.drop_index(op.f('ix_lecturer_option_is_deleted'), table_name='lecturer_option')
    op.drop_table('lecturer_option')
    op.drop_index(op.f('ix_course_option_is_deleted'), table_name='course_option')
    op.drop_table('course_option')
    op.drop_index(op.f('ix_course_department_is_deleted'), table_name='course_department')
    op.drop_table('course_department')
    op.drop_index('ix_class_group_option_id', table_name='class_group')
    op.drop_index(op.f('ix_class_group_is_deleted'), table_name='class_group')
    op.drop_index(op.f('ix_class_group_is_active'), table_name='class_group')
    op.drop_table('class_group')
    op.drop_index(op.f('ix_option_is_deleted'), table_name='option')
    op.drop_index(op.f('ix_option_is_active'), table_name='option')
    op.drop_index('ix_option_department_id', table_name='option')
    op.drop_table('option')
    op.drop_index(op.f('ix_lecturer_department_is_deleted'), table_name='lecturer_department')
    op.drop_table('lecturer_department')
    op.drop_index(op.f('ix_lecturer_institution_is_deleted'), table_name='lecturer_institution')
    op.drop_table('lecturer_institution')
    # ### end Alembic commands ###
