"""fix_response_log_timezone

Revision ID: a76a168cf7e7
Revises: 70966d28b322
Create Date: 2026-04-28 16:02:54.727963

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'a76a168cf7e7'
down_revision: Union[str, None] = '70966d28b322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_chunk', 'embedding',
               existing_type=postgresql.JSONB(),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True,
               postgresql_using='embedding::text::vector(1536)')
    op.alter_column('student_response_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_response_log', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('resource_chunk', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
