"""refactor_academic_cleanup

Revision ID: 66198628dbc3
Revises: 35747f0afc1c
Create Date: 2026-06-03 23:49:33.275463

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '66198628dbc3'
down_revision: Union[str, None] = '35747f0afc1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually create Enum if it doesn't exist
    section_status_enum = sa.Enum('ACTIVE', 'ARCHIVED', 'GRADUATED', 'SUSPENDED', name='classsectionstatus')
    section_status_enum.create(op.get_bind(), checkfirst=True)

    # op.drop_table('lecturer_option') # Handled by previous head or manual check
    
    # Fix Class Section columns if they were missed or partially created
    # Check if academic_year exists first to avoid duplicate column errors
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='class_section' AND column_name='academic_year'"))
    if not res.first():
        op.add_column('class_section', sa.Column('academic_year', sa.String(length=100), nullable=False, server_default='2026'))
    
    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='class_section' AND column_name='status'"))
    if not res.first():
        op.add_column('class_section', sa.Column('status', section_status_enum, server_default='ACTIVE', nullable=False))

    # Clean up obsolete columns from Course
    try:
        op.drop_column('course', 'option_name')
    except: pass
    try:
        op.drop_column('course', 'academic_year')
    except: pass
    try:
        op.drop_column('course', 'department_name')
    except: pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
