"""add_settings_and_integrations_to_institution

Revision ID: 9ee2a3a75f8a
Revises: 9a273e2ef00a
Create Date: 2026-05-23 19:10:59.796343

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '9ee2a3a75f8a'
down_revision: Union[str, None] = '9a273e2ef00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('institution', sa.Column('integrations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('subject', sa.Column('institution_id', sa.UUID(), nullable=False))
    op.drop_constraint('uq_subject_dept_code', 'subject', type_='unique')
    op.create_index('ix_subject_institution_id', 'subject', ['institution_id'], unique=False)
    op.create_unique_constraint('uq_subject_inst_code', 'subject', ['institution_id', 'code'])
    op.create_foreign_key(None, 'subject', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_constraint('uq_subject_inst_code', 'subject', type_='unique')
    op.drop_index('ix_subject_institution_id', table_name='subject')
    op.create_unique_constraint('uq_subject_dept_code', 'subject', ['department_id', 'code'])
    op.drop_column('subject', 'institution_id')
    op.drop_column('institution', 'integrations')
    op.drop_column('institution', 'settings')
    # ### end Alembic commands ###
