"""multi_institution_shift

Revision ID: c224a53175be
Revises: 3d2a1b4c5d6e
Create Date: 2026-05-21 21:11:04.421238

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'c224a53175be'
down_revision: Union[str, None] = '3d2a1b4c5d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_group', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('class_group', sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_class_group_external_id'), 'class_group', ['external_id'], unique=False)
    op.add_column('class_section', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('class_section', sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_class_section_external_id'), 'class_section', ['external_id'], unique=False)
    op.add_column('course', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('course', sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_course_external_id'), 'course', ['external_id'], unique=False)
    op.add_column('department', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('department', sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_department_external_id'), 'department', ['external_id'], unique=False)
    op.add_column('institution', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('institution', sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_institution_external_id'), 'institution', ['external_id'], unique=False)
    op.add_column('option', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('option', sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_option_external_id'), 'option', ['external_id'], unique=False)
    op.add_column('user', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True, comment='External ID from MIS/SIS systems'))
    op.add_column('user', sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True, comment='Source system name (e.g. RP_MIS)'))
    op.create_index(op.f('ix_user_external_id'), 'user', ['external_id'], unique=False)
    op.add_column('user_profile', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.add_column('user_profile', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('user_profile', sa.Column('option_id', sa.UUID(), nullable=True))
    op.add_column('user_profile', sa.Column('class_section_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_profile_class_section_id'), 'user_profile', ['class_section_id'], unique=False)
    op.create_index(op.f('ix_user_profile_department_id'), 'user_profile', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_profile_institution_id'), 'user_profile', ['institution_id'], unique=False)
    op.create_index(op.f('ix_user_profile_option_id'), 'user_profile', ['option_id'], unique=False)
    op.create_foreign_key(None, 'user_profile', 'class_section', ['class_section_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_profile', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_profile', 'institution', ['institution_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_profile', 'option', ['option_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_index(op.f('ix_user_profile_option_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_institution_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_department_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_class_section_id'), table_name='user_profile')
    op.drop_column('user_profile', 'class_section_id')
    op.drop_column('user_profile', 'option_id')
    op.drop_column('user_profile', 'department_id')
    op.drop_column('user_profile', 'institution_id')
    op.drop_index(op.f('ix_user_external_id'), table_name='user')
    op.drop_column('user', 'source_system')
    op.drop_column('user', 'external_id')
    op.drop_column('user', 'onboarding_completed')
    op.drop_index(op.f('ix_option_external_id'), table_name='option')
    op.drop_column('option', 'source_system')
    op.drop_column('option', 'external_id')
    op.drop_index(op.f('ix_institution_external_id'), table_name='institution')
    op.drop_column('institution', 'source_system')
    op.drop_column('institution', 'external_id')
    op.drop_index(op.f('ix_department_external_id'), table_name='department')
    op.drop_column('department', 'source_system')
    op.drop_column('department', 'external_id')
    op.drop_index(op.f('ix_course_external_id'), table_name='course')
    op.drop_column('course', 'source_system')
    op.drop_column('course', 'external_id')
    op.drop_index(op.f('ix_class_section_external_id'), table_name='class_section')
    op.drop_column('class_section', 'source_system')
    op.drop_column('class_section', 'external_id')
    op.drop_index(op.f('ix_class_group_external_id'), table_name='class_group')
    op.drop_column('class_group', 'source_system')
    op.drop_column('class_group', 'external_id')
    # ### end Alembic commands ###
