"""Add case_study_context to Question

Revision ID: e968e541c2a0
Revises: 78173997c983
Create Date: 2026-06-08 09:39:59.907298

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic
revision: str = 'e968e541c2a0'
down_revision: Union[str, None] = '78173997c983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_grade_review', sa.Column('response_id', sa.UUID(), nullable=True))
    op.add_column('ai_grade_review', sa.Column('submission_grade_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_grade_review_response_id'), 'ai_grade_review', ['response_id'], unique=False)
    op.create_index(op.f('ix_ai_grade_review_submission_grade_id'), 'ai_grade_review', ['submission_grade_id'], unique=False)
    op.create_foreign_key('ai_grade_review_submission_grade_id_fkey', 'ai_grade_review', 'submission_grade', ['submission_grade_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('ai_grade_review_response_id_fkey', 'ai_grade_review', 'student_response', ['response_id'], ['id'], ondelete='CASCADE')
    op.add_column('question', sa.Column('case_study_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'case_study_context')
    op.drop_constraint('ai_grade_review_response_id_fkey', 'ai_grade_review', type_='foreignkey')
    op.drop_constraint('ai_grade_review_submission_grade_id_fkey', 'ai_grade_review', type_='foreignkey')
    op.drop_index(op.f('ix_ai_grade_review_submission_grade_id'), table_name='ai_grade_review')
    op.drop_index(op.f('ix_ai_grade_review_response_id'), table_name='ai_grade_review')
    op.drop_column('ai_grade_review', 'submission_grade_id')
    op.drop_column('ai_grade_review', 'response_id')
    # ### end Alembic commands ###
