"""relax_hierarchy_unique_constraints

Revision ID: eecf2d2063ae
Revises: 5201ea081345
Create Date: 2026-06-03 21:27:50.109057

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'eecf2d2063ae'
down_revision: Union[str, None] = '5201ea081345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_college_inst_code'), 'college', type_='unique')
    op.create_unique_constraint('uq_college_scope_code', 'college', ['institution_id', 'campus_id', 'code'])
    op.drop_constraint(op.f('uq_department_inst_code'), 'department', type_='unique')
    op.create_unique_constraint('uq_department_scope_code', 'department', ['institution_id', 'campus_id', 'college_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_department_scope_code', 'department', type_='unique')
    op.create_unique_constraint(op.f('uq_department_inst_code'), 'department', ['institution_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_college_scope_code', 'college', type_='unique')
    op.create_unique_constraint(op.f('uq_college_inst_code'), 'college', ['institution_id', 'code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
