"""make_teaching_workspace_fields_nullable

Revision ID: 5efaae606097
Revises: 6743436fcf55
Create Date: 2026-06-03 18:05:01.051371

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '5efaae606097'
down_revision: Union[str, None] = '6743436fcf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teaching_workspace', 'class_section_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('teaching_workspace', 'academic_period_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teaching_workspace', 'academic_period_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('teaching_workspace', 'class_section_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
