"""sync_password_reset_token_schema

Revision ID: 877efb5d92e9
Revises: 6887123f7ad9
Create Date: 2026-04-28 11:29:29.719415

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '877efb5d92e9'
down_revision: Union[str, None] = '6887123f7ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_academic_period_institution_id_is_active', table_name='academic_period')
    op.drop_index('ix_academic_period_institution_id_period_type', table_name='academic_period')
    op.create_unique_constraint('uq_academic_period_inst_name', 'academic_period', ['institution_id', 'name'])
    op.drop_index('ix_assessment_course_id', table_name='assessment')
    op.drop_index('ix_assessment_draft_is_complete', table_name='assessment')
    op.drop_index('ix_assessment_reassessment_of_id', table_name='assessment')
    op.drop_index('ix_assessment_status', table_name='assessment')
    op.drop_index('ix_assessment_subject_id', table_name='assessment')
    op.drop_index('ix_assessment_attempt_assessment_id', table_name='assessment_attempt')
    op.drop_index('ix_assessment_attempt_student_id', table_name='assessment_attempt')
    op.drop_index('ix_assessment_autosave_assessment_id', table_name='assessment_autosave')
    op.drop_index('ix_assessment_draft_progress_assessment_id', table_name='assessment_draft_progress')
    op.drop_index('ix_assessment_publish_validation_assessment_id', table_name='assessment_publish_validation')
    op.drop_index('ix_assessment_question_added_via', table_name='assessment_question')
    op.drop_index('ix_assessment_question_assessment_id', table_name='assessment_question')
    op.drop_index('ix_assessment_result_assessment_id', table_name='assessment_result')
    op.drop_index('ix_assessment_result_integrity_hold', table_name='assessment_result')
    op.drop_index('ix_assessment_result_student_id', table_name='assessment_result')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_id', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_id', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_type', table_name='audit_log')
    op.drop_index('ix_class_section_course_id', table_name='class_section')
    op.add_column('course', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_index('ix_course_academic_period_id_is_active', table_name='course')
    op.drop_index('ix_course_department_id_is_active', table_name='course')
    op.drop_index('ix_course_institution_id_is_active', table_name='course')
    op.drop_constraint('uq_course_institution_code_period', 'course', type_='unique')
    op.create_unique_constraint('uq_course_inst_code_period', 'course', ['institution_id', 'code', 'academic_period_id'])
    op.drop_constraint('course_department_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'department', ['department_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('course', 'title')
    op.drop_index('ix_department_institution_id_is_active', table_name='department')
    op.drop_index('ix_department_is_active', table_name='department')
    op.drop_constraint('uq_department_institution_code', 'department', type_='unique')
    op.create_unique_constraint('uq_department_inst_code', 'department', ['institution_id', 'code'])
    op.drop_constraint('department_institution_id_fkey', 'department', type_='foreignkey')
    op.create_foreign_key(None, 'department', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_integrity_event_attempt_id', table_name='integrity_event')
    op.drop_index('ix_integrity_flag_assessment_id', table_name='integrity_flag')
    op.drop_index('ix_integrity_flag_attempt_id', table_name='integrity_flag')
    op.drop_index('ix_lecturer_course_assignment_course_id', table_name='lecturer_course_assignment')
    op.drop_index('ix_lecturer_course_assignment_lecturer_id', table_name='lecturer_course_assignment')
    op.drop_index('ix_lecturer_course_assignment_lecturer_id_course_id', table_name='lecturer_course_assignment')
    op.drop_constraint('uq_lecturer_course_assignment_lecturer_course_role', 'lecturer_course_assignment', type_='unique')
    op.create_unique_constraint('uq_lecturer_course_role', 'lecturer_course_assignment', ['lecturer_id', 'course_id', 'assignment_role'])
    op.drop_index('ix_lecturer_material_course_id', table_name='lecturer_material')
    op.drop_index('ix_lecturer_material_lecturer_id', table_name='lecturer_material')
    op.drop_index('ix_notification_recipient_id', table_name='notification')
    op.add_column('password_reset_token', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('password_reset_token', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('password_reset_token', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('password_reset_token', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 hash of the raw token sent to the user',
               existing_nullable=False)
    op.alter_column('password_reset_token', 'token_purpose',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='password_reset | email_verification',
               existing_nullable=False)
    op.drop_index('ix_password_reset_token_user_id', table_name='password_reset_token')
    op.create_index(op.f('ix_password_reset_token_is_deleted'), 'password_reset_token', ['is_deleted'], unique=False)
    op.drop_index('ix_question_is_active', table_name='question')
    op.drop_index('ix_question_is_in_question_bank', table_name='question')
    op.drop_index('ix_question_bank_entry_added_by_id', table_name='question_bank_entry')
    op.drop_index('ix_question_bank_entry_difficulty', table_name='question_bank_entry')
    op.drop_index('ix_question_bank_entry_is_active', table_name='question_bank_entry')
    op.drop_index('ix_question_bank_entry_source_type', table_name='question_bank_entry')
    op.drop_index('ix_question_bank_entry_subject_id', table_name='question_bank_entry')
    op.drop_index('ix_question_option_question_id', table_name='question_option')
    op.add_column('refresh_token', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('refresh_token', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('refresh_token', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('refresh_token', 'jti',
               existing_type=sa.VARCHAR(length=36),
               comment='JWT ID claim',
               existing_comment='JWT ID claim — unique identifier for this token',
               existing_nullable=False)
    op.alter_column('refresh_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Token expiry — after this the token is invalid regardless of revocation',
               existing_nullable=False)
    op.alter_column('refresh_token', 'revoked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True if this token has been explicitly revoked',
               existing_nullable=False)
    op.alter_column('refresh_token', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when this token was revoked',
               existing_nullable=True)
    op.alter_column('refresh_token', 'device_hint',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='User-Agent or device identifier (for display purposes only)',
               existing_nullable=True)
    op.alter_column('refresh_token', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='Client IP at token issuance',
               existing_nullable=True)
    op.drop_index('ix_refresh_token_user_id', table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_is_deleted'), 'refresh_token', ['is_deleted'], unique=False)
    op.drop_index('ix_reminder_recipient_id', table_name='reminder')
    op.drop_index('ix_resource_chunk_student_resource_id', table_name='resource_chunk')
    op.drop_index('ix_result_breakdown_attempt_id', table_name='result_breakdown')
    op.drop_index('ix_scheduled_event_user_id', table_name='scheduled_event')
    op.drop_index('ix_security_event_event_type', table_name='security_event')
    op.drop_index('ix_security_event_ip_address', table_name='security_event')
    op.drop_index('ix_security_event_severity', table_name='security_event')
    op.drop_index('ix_security_event_user_id', table_name='security_event')
    op.alter_column('student_enrollment', 'withdrawn_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_student_enrollment_class_section_id', table_name='student_enrollment')
    op.drop_index('ix_student_enrollment_student_id', table_name='student_enrollment')
    op.drop_index('ix_student_resource_student_id', table_name='student_resource')
    op.drop_index('ix_subject_institution_id_department_id', table_name='subject')
    op.drop_index('ix_subject_institution_id_is_active', table_name='subject')
    op.drop_constraint('uq_subject_institution_code', 'subject', type_='unique')
    op.create_unique_constraint('uq_subject_inst_title', 'subject', ['institution_id', 'title'])
    op.drop_column('subject', 'code')
    op.drop_index('ix_supervision_session_assessment_id', table_name='supervision_session')
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='User role: STUDENT | LECTURER | ADMIN',
               existing_comment='User role: student | lecturer | admin',
               existing_nullable=False)
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='Account status',
               existing_comment='Account status: pending_verification | active | suspended | inactive',
               existing_nullable=False)
    op.alter_column('user', 'email_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True after email address has been verified',
               existing_nullable=False)
    op.alter_column('user', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when email was verified',
               existing_nullable=True)
    op.alter_column('user', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last successful login',
               existing_nullable=True)
    op.alter_column('user', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of consecutive failed login attempts',
               existing_nullable=False)
    op.alter_column('user', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Account login is blocked until this UTC datetime',
               existing_nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_role', table_name='user')
    op.drop_index('ix_user_status', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.alter_column('user_profile', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_profile', 'display_name',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Preferred display name (overrides first + last)',
               existing_nullable=True)
    op.alter_column('user_profile', 'student_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Institution-assigned student ID (students only)',
               existing_nullable=True)
    op.alter_column('user_profile', 'staff_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Institution-assigned staff ID (lecturers/admins)',
               existing_nullable=True)
    op.drop_index('ix_user_profile_user_id', table_name='user_profile')
    op.create_unique_constraint(None, 'user_profile', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_index('ix_user_profile_user_id', 'user_profile', ['user_id'], unique=True)
    op.alter_column('user_profile', 'staff_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Institution-assigned staff ID (lecturers/admins)',
               existing_nullable=True)
    op.alter_column('user_profile', 'student_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Institution-assigned student ID (students only)',
               existing_nullable=True)
    op.alter_column('user_profile', 'display_name',
               existing_type=sa.VARCHAR(length=150),
               comment='Preferred display name (overrides first + last)',
               existing_nullable=True)
    op.alter_column('user_profile', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_status', 'user', ['status'], unique=False)
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('user', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Account login is blocked until this UTC datetime',
               existing_nullable=True)
    op.alter_column('user', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               comment='Number of consecutive failed login attempts',
               existing_nullable=False)
    op.alter_column('user', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last successful login',
               existing_nullable=True)
    op.alter_column('user', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when email was verified',
               existing_nullable=True)
    op.alter_column('user', 'email_verified',
               existing_type=sa.BOOLEAN(),
               comment='True after email address has been verified',
               existing_nullable=False)
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='Account status: pending_verification | active | suspended | inactive',
               existing_comment='Account status',
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='User role: student | lecturer | admin',
               existing_comment='User role: STUDENT | LECTURER | ADMIN',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index('ix_supervision_session_assessment_id', 'supervision_session', ['assessment_id'], unique=False)
    op.add_column('subject', sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint('uq_subject_inst_title', 'subject', type_='unique')
    op.create_unique_constraint('uq_subject_institution_code', 'subject', ['institution_id', 'code'])
    op.create_index('ix_subject_institution_id_is_active', 'subject', ['institution_id', 'is_active'], unique=False)
    op.create_index('ix_subject_institution_id_department_id', 'subject', ['institution_id', 'department_id'], unique=False)
    op.create_index('ix_student_resource_student_id', 'student_resource', ['student_id'], unique=False)
    op.create_index('ix_student_enrollment_student_id', 'student_enrollment', ['student_id'], unique=False)
    op.create_index('ix_student_enrollment_class_section_id', 'student_enrollment', ['class_section_id'], unique=False)
    op.alter_column('student_enrollment', 'withdrawn_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index('ix_security_event_user_id', 'security_event', ['user_id'], unique=False)
    op.create_index('ix_security_event_severity', 'security_event', ['severity'], unique=False)
    op.create_index('ix_security_event_ip_address', 'security_event', ['ip_address'], unique=False)
    op.create_index('ix_security_event_event_type', 'security_event', ['event_type'], unique=False)
    op.create_index('ix_scheduled_event_user_id', 'scheduled_event', ['user_id'], unique=False)
    op.create_index('ix_result_breakdown_attempt_id', 'result_breakdown', ['attempt_id'], unique=False)
    op.create_index('ix_resource_chunk_student_resource_id', 'resource_chunk', ['student_resource_id'], unique=False)
    op.create_index('ix_reminder_recipient_id', 'reminder', ['recipient_id'], unique=False)
    op.drop_index(op.f('ix_refresh_token_is_deleted'), table_name='refresh_token')
    op.create_index('ix_refresh_token_user_id', 'refresh_token', ['user_id'], unique=False)
    op.alter_column('refresh_token', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Client IP at token issuance',
               existing_nullable=True)
    op.alter_column('refresh_token', 'device_hint',
               existing_type=sa.VARCHAR(length=500),
               comment='User-Agent or device identifier (for display purposes only)',
               existing_nullable=True)
    op.alter_column('refresh_token', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when this token was revoked',
               existing_nullable=True)
    op.alter_column('refresh_token', 'revoked',
               existing_type=sa.BOOLEAN(),
               comment='True if this token has been explicitly revoked',
               existing_nullable=False)
    op.alter_column('refresh_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Token expiry — after this the token is invalid regardless of revocation',
               existing_nullable=False)
    op.alter_column('refresh_token', 'jti',
               existing_type=sa.VARCHAR(length=36),
               comment='JWT ID claim — unique identifier for this token',
               existing_comment='JWT ID claim',
               existing_nullable=False)
    op.alter_column('refresh_token', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('refresh_token', 'deleted_at')
    op.drop_column('refresh_token', 'is_deleted')
    op.create_index('ix_question_option_question_id', 'question_option', ['question_id'], unique=False)
    op.create_index('ix_question_bank_entry_subject_id', 'question_bank_entry', ['subject_id'], unique=False)
    op.create_index('ix_question_bank_entry_source_type', 'question_bank_entry', ['source_type'], unique=False)
    op.create_index('ix_question_bank_entry_is_active', 'question_bank_entry', ['is_active'], unique=False)
    op.create_index('ix_question_bank_entry_difficulty', 'question_bank_entry', ['difficulty'], unique=False)
    op.create_index('ix_question_bank_entry_added_by_id', 'question_bank_entry', ['added_by_id'], unique=False)
    op.create_index('ix_question_is_in_question_bank', 'question', ['is_in_question_bank'], unique=False)
    op.create_index('ix_question_is_active', 'question', ['is_active'], unique=False)
    op.drop_index(op.f('ix_password_reset_token_is_deleted'), table_name='password_reset_token')
    op.create_index('ix_password_reset_token_user_id', 'password_reset_token', ['user_id'], unique=False)
    op.alter_column('password_reset_token', 'token_purpose',
               existing_type=sa.VARCHAR(length=30),
               comment='password_reset | email_verification',
               existing_nullable=False)
    op.alter_column('password_reset_token', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 hash of the raw token sent to the user',
               existing_nullable=False)
    op.alter_column('password_reset_token', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('password_reset_token', 'deleted_at')
    op.drop_column('password_reset_token', 'is_deleted')
    op.create_index('ix_notification_recipient_id', 'notification', ['recipient_id'], unique=False)
    op.create_index('ix_lecturer_material_lecturer_id', 'lecturer_material', ['lecturer_id'], unique=False)
    op.create_index('ix_lecturer_material_course_id', 'lecturer_material', ['course_id'], unique=False)
    op.drop_constraint('uq_lecturer_course_role', 'lecturer_course_assignment', type_='unique')
    op.create_unique_constraint('uq_lecturer_course_assignment_lecturer_course_role', 'lecturer_course_assignment', ['lecturer_id', 'course_id', 'assignment_role'])
    op.create_index('ix_lecturer_course_assignment_lecturer_id_course_id', 'lecturer_course_assignment', ['lecturer_id', 'course_id'], unique=False)
    op.create_index('ix_lecturer_course_assignment_lecturer_id', 'lecturer_course_assignment', ['lecturer_id'], unique=False)
    op.create_index('ix_lecturer_course_assignment_course_id', 'lecturer_course_assignment', ['course_id'], unique=False)
    op.create_index('ix_integrity_flag_attempt_id', 'integrity_flag', ['attempt_id'], unique=False)
    op.create_index('ix_integrity_flag_assessment_id', 'integrity_flag', ['assessment_id'], unique=False)
    op.create_index('ix_integrity_event_attempt_id', 'integrity_event', ['attempt_id'], unique=False)
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.create_foreign_key('department_institution_id_fkey', 'department', 'institution', ['institution_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_department_inst_code', 'department', type_='unique')
    op.create_unique_constraint('uq_department_institution_code', 'department', ['institution_id', 'code'])
    op.create_index('ix_department_is_active', 'department', ['is_active'], unique=False)
    op.create_index('ix_department_institution_id_is_active', 'department', ['institution_id', 'is_active'], unique=False)
    op.add_column('course', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_department_id_fkey', 'course', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_course_inst_code_period', 'course', type_='unique')
    op.create_unique_constraint('uq_course_institution_code_period', 'course', ['institution_id', 'code', 'academic_period_id'])
    op.create_index('ix_course_institution_id_is_active', 'course', ['institution_id', 'is_active'], unique=False)
    op.create_index('ix_course_department_id_is_active', 'course', ['department_id', 'is_active'], unique=False)
    op.create_index('ix_course_academic_period_id_is_active', 'course', ['academic_period_id', 'is_active'], unique=False)
    op.drop_column('course', 'name')
    op.create_index('ix_class_section_course_id', 'class_section', ['course_id'], unique=False)
    op.create_index('ix_audit_log_entity_type', 'audit_log', ['entity_type'], unique=False)
    op.create_index('ix_audit_log_entity_id', 'audit_log', ['entity_id'], unique=False)
    op.create_index('ix_audit_log_actor_id', 'audit_log', ['actor_id'], unique=False)
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_assessment_result_student_id', 'assessment_result', ['student_id'], unique=False)
    op.create_index('ix_assessment_result_integrity_hold', 'assessment_result', ['integrity_hold'], unique=False)
    op.create_index('ix_assessment_result_assessment_id', 'assessment_result', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_question_assessment_id', 'assessment_question', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_question_added_via', 'assessment_question', ['added_via'], unique=False)
    op.create_index('ix_assessment_publish_validation_assessment_id', 'assessment_publish_validation', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_draft_progress_assessment_id', 'assessment_draft_progress', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_autosave_assessment_id', 'assessment_autosave', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_attempt_student_id', 'assessment_attempt', ['student_id'], unique=False)
    op.create_index('ix_assessment_attempt_assessment_id', 'assessment_attempt', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_subject_id', 'assessment', ['subject_id'], unique=False)
    op.create_index('ix_assessment_status', 'assessment', ['status'], unique=False)
    op.create_index('ix_assessment_reassessment_of_id', 'assessment', ['reassessment_of_id'], unique=False)
    op.create_index('ix_assessment_draft_is_complete', 'assessment', ['draft_is_complete'], unique=False)
    op.create_index('ix_assessment_course_id', 'assessment', ['course_id'], unique=False)
    op.drop_constraint('uq_academic_period_inst_name', 'academic_period', type_='unique')
    op.create_index('ix_academic_period_institution_id_period_type', 'academic_period', ['institution_id', 'period_type'], unique=False)
    op.create_index('ix_academic_period_institution_id_is_active', 'academic_period', ['institution_id', 'is_active'], unique=False)
    # ### end Alembic commands ###
