"""link_resources_to_academic_resource

Revision ID: 16ebb70a261d
Revises: 6d36f3c770e4
Create Date: 2026-06-16 08:24:44.973711

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '16ebb70a261d'
down_revision: Union[str, None] = '6d36f3c770e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer_material', sa.Column('academic_resource_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lecturer_material', 'academic_resources', ['academic_resource_id'], ['id'], ondelete='SET NULL')
    op.add_column('student_resource', sa.Column('academic_resource_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'student_resource', 'academic_resources', ['academic_resource_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_resource', type_='foreignkey')
    op.drop_column('student_resource', 'academic_resource_id')
    op.drop_constraint(None, 'lecturer_material', type_='foreignkey')
    op.drop_column('lecturer_material', 'academic_resource_id')
    # ### end Alembic commands ###
